var BiBDat_Docs_Info = 
{
    "analects": {
        "url": "http://www.ctext.org/analects/zh",
        "dtv": "-480",
        "dts": " [春秋 - 战国] 公元前480年-公元前350年",
        "eng": "analects",
        "chn": "论语",
        "idx": "000",
        "pinyin": "LunYun",
        "txtlen": 15962,
        "dynacat": "先秦两汉",
        "school": "儒家",
        "srcDir": "../../ctext/main/dwnload/nodjsapp/out/ctext_res_clean",
        "srcFileType": ".htm",
        "srcFileNameKeyStr": "analects_",
        "author": "孔子弟子及再传弟子记录孔子及其弟子言行而编成的语录集",
        "numVers": "3. (古论,鲁论,齐论) [TangMingGui2006article]",
        "brief": "孔子的政治、审美、道德伦理,功利等价值思想,教育、文学、哲学以及立身处世.清朝赵翼解释说：“语者，圣人之语言，论者，诸儒之讨论也。”",
        "doctype": "misc",
        "title": "ttt",
        "abstract": "tttt",
        "annote": "孔子弟子及再传弟子记录孔子及其弟子言行而编成的语录集\n\n孔子（公元前551年9月28日－公元前479年4月11日），子姓，孔氏，名丘，字仲尼，鲁国陬邑（今山东曲阜）人，祖籍宋国，中国古代思想家、教育家，儒家学派创始人。 [1-4] \n\n\n3. (古论,鲁论,齐论) [TangMingGui2006article]\n\n孔子的政治、审美、道德伦理,功利等价值思想,教育、文学、哲学以及立身处世.清朝赵翼解释说：“语者，圣人之语言，论者，诸儒之讨论也。”",
        "mynotes": "ttt"
    },
    "mengzi": {
        "url": "http://www.ctext.org/mengzi/zh",
        "dtv": "-340",
        "dts": " [战国] 公元前340年-公元前250年",
        "eng": "mengzi",
        "chn": "孟子",
        "idx": "050",
        "txtlen": 35426,
        "dynacat": "先秦两汉",
        "school": "儒家",
        "srcDir": "../../ctext/main/dwnload/nodjsapp/out/ctext_res_clean",
        "srcFileType": ".htm",
        "srcFileNameKeyStr": "mengzi_",
        "author": "孟子,名轲,字子舆,又字子车,子居. 汉族",
        "numVers": "many. 《汉书·艺文志》著录《孟子》十一篇，现存七篇十四卷。总字数三万五千余字，286章。相传另有《孟子外书》四篇，已佚（今本《孟子外书》系明姚士粦伪作）。",
        "brief": "",
        "doctype": "misc",
        "title": "先秦七子的历史人物",
        "abstract": "v. 《汉书·艺文志》著录《孟子》十一篇，现存七篇十四卷。总字数三万五千余字，286章。相传另有《孟子外书》四篇，已佚（今本《孟子外书》系明姚士粦伪作）。",
        "annote": "ver. 《汉书·艺文志》著录《孟子》十一篇，现存七篇十四卷。总字数三万五千余字，286章。相传另有《孟子外书》四篇，已佚（今本《孟子外书》系明姚士粦伪作）。\n\n孟子（前372年～前289年），战国时期鲁国人(今山东邹城人)，汉族。名轲，字子舆，又字子车、子居。父名激，母仉氏。字号在汉代以前的古书没有记载，但魏、晋之後却传出子车、子居、子舆等三个不同的字号，字号可能是後人的附会而未必可信。生卒年月因史传未记载而有许多的说法，",
        "editor": "孟子弟子及再传弟子记录孔子及其弟子言行而编成的语录集."
    },
    "liji": {
        "url": "http://www.ctext.org/liji/zh",
        "dtv": "-475",
        "dts": " [战国 (公元前475年 - 公元前221年)]",
        "eng": "liji",
        "chn": "礼记",
        "idx": "044",
        "txtlen": 98089,
        "dynacat": "先秦两汉",
        "school": "儒家",
        "srcDir": "../../ctext/main/dwnload/nodjsapp/out/ctext_res_clean",
        "srcFileType": ".htm",
        "srcFileNameKeyStr": "liji_",
        "author": "",
        "numVers": "",
        "brief": ""
    },
    "xunzi": {
        "url": "http://www.ctext.org/xunzi/zh",
        "dtv": "-475",
        "dts": "[战国 (公元前475年 - 公元前221年)]",
        "eng": "xunzi",
        "chn": "荀子",
        "idx": "086",
        "txtlen": 75242,
        "dynacat": "先秦两汉",
        "school": "儒家",
        "srcDir": "../../ctext/main/dwnload/nodjsapp/out/ctext_res_clean",
        "srcFileType": ".htm",
        "srcFileNameKeyStr": "xunzi_",
        "author": "",
        "numVers": "",
        "brief": ""
    },
    "xiao-jing": {
        "url": "http://www.ctext.org/xiao-jing/zh",
        "dtv": "-475",
        "dts": " [战国 (公元前475年 - 公元前221年)]",
        "eng": "xiao-jing",
        "chn": "孝经",
        "idx": "081",
        "txtlen": 1840,
        "dynacat": "先秦两汉",
        "school": "儒家",
        "srcDir": "../../ctext/main/dwnload/nodjsapp/out/ctext_res_clean",
        "srcFileType": ".htm",
        "srcFileNameKeyStr": "xiao-jing_",
        "author": "",
        "numVers": "",
        "brief": ""
    },
    "shuo-yuan": {
        "url": "http://www.ctext.org/shuo-yuan/zh",
        "dtv": "-206",
        "dts": " [西汉 (公元前206年 - 9年)] 刘向著",
        "eng": "shuo-yuan",
        "chn": "说苑",
        "idx": "070",
        "txtlen": 110659,
        "dynacat": "先秦两汉",
        "school": "儒家",
        "srcDir": "../../ctext/main/dwnload/nodjsapp/out/ctext_res_clean",
        "srcFileType": ".htm",
        "srcFileNameKeyStr": "shuo-yuan_",
        "author": "",
        "numVers": "",
        "brief": ""
    },
    "chun-qiu-fan-lu": {
        "url": "http://www.ctext.org/chun-qiu-fan-lu/zh",
        "dtv": "-206",
        "dts": "[西汉 (公元前206年 - 9年)] 董仲舒著",
        "eng": "chun-qiu-fan-lu",
        "chn": "春秋繁露",
        "idx": "007",
        "txtlen": 58436,
        "dynacat": "先秦两汉",
        "school": "儒家",
        "srcDir": "../../ctext/main/dwnload/nodjsapp/out/ctext_res_clean",
        "srcFileType": ".htm",
        "srcFileNameKeyStr": "chun-qiu-fan-lu_",
        "author": "",
        "numVers": "",
        "brief": ""
    },
    "han-shi-wai-zhuan": {
        "url": "http://www.ctext.org/han-shi-wai-zhuan/zh",
        "dtv": "-180",
        "dts": " [西汉] 公元前180年-公元前120年",
        "eng": "han-shi-wai-zhuan",
        "chn": "韩诗外传",
        "idx": "026",
        "txtlen": 50870,
        "dynacat": "先秦两汉",
        "school": "儒家",
        "srcDir": "../../ctext/main/dwnload/nodjsapp/out/ctext_res_clean",
        "srcFileType": ".htm",
        "srcFileNameKeyStr": "han-shi-wai-zhuan_",
        "author": "",
        "numVers": "",
        "brief": ""
    },
    "da-dai-li-ji": {
        "url": "http://www.ctext.org/da-dai-li-ji/zh",
        "dtv": "-400",
        "dts": " [东汉] 100年-200年,孔子的学生及战国时期儒学学者的作品。汉朝学者戴德将汉初刘向收集的130篇综合简",
        "eng": "da-dai-li-ji",
        "chn": "大戴礼记",
        "idx": "009",
        "txtlen": 37782,
        "dynacat": "先秦两汉",
        "school": "儒家",
        "srcDir": "../../ctext/main/dwnload/nodjsapp/out/ctext_res_clean",
        "srcFileType": ".htm",
        "srcFileNameKeyStr": "da-dai-li-ji_",
        "author": "老子,姓李,名耳,字聃,一字伯阳,或曰谥伯阳",
        "numVers": "",
        "brief": "",
        "doctype": "misc",
        "title": "(先秦七子的历史人物)"
    },
    "bai-hu-tong": {
        "url": "http://www.ctext.org/bai-hu-tong/zh",
        "dtv": "79",
        "dts": " [东汉] 79年-92年 班固著",
        "eng": "bai-hu-tong",
        "chn": "白虎通德论",
        "idx": "002",
        "txtlen": 45337,
        "dynacat": "先秦两汉",
        "school": "儒家",
        "srcDir": "../../ctext/main/dwnload/nodjsapp/out/ctext_res_clean",
        "srcFileType": ".htm",
        "srcFileNameKeyStr": "bai-hu-tong_",
        "author": "",
        "numVers": "",
        "brief": ""
    },
    "xin-shu": {
        "url": "http://www.ctext.org/xin-shu/zh",
        "dtv": "-206",
        "dts": " [西汉 (公元前206年 - 9年)] 贾谊著",
        "eng": "xin-shu",
        "chn": "新书",
        "idx": "083",
        "txtlen": 41960,
        "dynacat": "先秦两汉",
        "school": "儒家",
        "srcDir": "../../ctext/main/dwnload/nodjsapp/out/ctext_res_clean",
        "srcFileType": ".htm",
        "srcFileNameKeyStr": "xin-shu_",
        "author": "",
        "numVers": "",
        "brief": ""
    },
    "xin-xu": {
        "url": "http://www.ctext.org/xin-xu/zh",
        "dtv": "-206",
        "dts": " [西汉 (公元前206年 - 9年)] 刘向著",
        "eng": "xin-xu",
        "chn": "新序",
        "idx": "084",
        "txtlen": 47585,
        "dynacat": "先秦两汉",
        "school": "儒家",
        "srcDir": "../../ctext/main/dwnload/nodjsapp/out/ctext_res_clean",
        "srcFileType": ".htm",
        "srcFileNameKeyStr": "xin-xu_",
        "author": "",
        "numVers": "",
        "brief": ""
    },
    "yangzi-fayan": {
        "url": "http://www.ctext.org/yangzi-fayan/zh",
        "dtv": "-33",
        "dts": " [西汉 - 新] 公元前33年-18年 扬雄著",
        "eng": "yangzi-fayan",
        "chn": "扬子法言",
        "idx": "089",
        "txtlen": 14637,
        "dynacat": "先秦两汉",
        "school": "儒家",
        "srcDir": "../../ctext/main/dwnload/nodjsapp/out/ctext_res_clean",
        "srcFileType": ".htm",
        "srcFileNameKeyStr": "yangzi-fayan_",
        "author": "",
        "numVers": "",
        "brief": ""
    },
    "zhong-lun": {
        "url": "http://www.ctext.org/zhong-lun/zh",
        "dtv": "25",
        "dts": " [东汉 (25年 - 220年)] 徐干著",
        "eng": "zhong-lun",
        "chn": "中论",
        "idx": "097",
        "txtlen": 22032,
        "dynacat": "先秦两汉",
        "school": "儒家",
        "srcDir": "../../ctext/main/dwnload/nodjsapp/out/ctext_res_clean",
        "srcFileType": ".htm",
        "srcFileNameKeyStr": "zhong-lun_",
        "author": "",
        "numVers": "",
        "brief": ""
    },
    "kongzi-jiayu": {
        "url": "http://www.ctext.org/kongzi-jiayu/zh",
        "dtv": "-206",
        "dts": "[汉 (公元前206年 - 220年)]",
        "eng": "kongzi-jiayu",
        "chn": "孔子家语",
        "idx": "040",
        "txtlen": 56952,
        "dynacat": "先秦两汉",
        "school": "儒家",
        "srcDir": "../../ctext/main/dwnload/nodjsapp/out/ctext_res_clean",
        "srcFileType": ".htm",
        "srcFileNameKeyStr": "kongzi-jiayu_",
        "author": "",
        "numVers": "",
        "brief": ""
    },
    "qian-fu-lun": {
        "url": "http://www.ctext.org/qian-fu-lun/zh",
        "dtv": "102",
        "dts": " [东汉] 102年-167年 王符著",
        "eng": "qian-fu-lun",
        "chn": "潜夫论",
        "idx": "056",
        "txtlen": 45076,
        "dynacat": "先秦两汉",
        "school": "儒家",
        "srcDir": "../../ctext/main/dwnload/nodjsapp/out/ctext_res_clean",
        "srcFileType": ".htm",
        "srcFileNameKeyStr": "qian-fu-lun_",
        "author": "",
        "numVers": "",
        "brief": ""
    },
    "lunheng": {
        "url": "http://www.ctext.org/lunheng/zh",
        "dtv": "80",
        "dts": "[东汉] 80年 王充著",
        "eng": "lunheng",
        "chn": "论衡",
        "idx": "047",
        "txtlen": 210068,
        "dynacat": "先秦两汉",
        "school": "儒家",
        "srcDir": "../../ctext/main/dwnload/nodjsapp/out/ctext_res_clean",
        "srcFileType": ".htm",
        "srcFileNameKeyStr": "lunheng_",
        "author": "",
        "numVers": "",
        "brief": ""
    },
    "taixuanjing": {
        "url": "http://www.ctext.org/taixuanjing/zh",
        "dtv": "-33",
        "dts": "[东汉] 公元前33年-18年 扬雄著",
        "eng": "taixuanjing",
        "chn": "太玄经",
        "idx": "074",
        "txtlen": 24207,
        "dynacat": "先秦两汉",
        "school": "儒家",
        "srcDir": "../../ctext/main/dwnload/nodjsapp/out/ctext_res_clean",
        "srcFileType": ".htm",
        "srcFileNameKeyStr": "taixuanjing_"
    },
    "fengsutongyi": {
        "url": "http://www.ctext.org/fengsutongyi/zh",
        "dtv": "190",
        "dts": " [东汉] 190年-200年",
        "eng": "fengsutongyi",
        "chn": "风俗通义",
        "idx": "016",
        "txtlen": 35002,
        "dynacat": "先秦两汉",
        "school": "儒家",
        "srcDir": "../../ctext/main/dwnload/nodjsapp/out/ctext_res_clean",
        "srcFileType": ".htm",
        "srcFileNameKeyStr": "fengsutongyi_"
    },
    "kongcongzi": {
        "url": "http://www.ctext.org/kongcongzi/zh",
        "dtv": "-250",
        "dts": " [东汉 - 三国 (25年 - 265年)]作者：孔鲋　春秋, 孔子八世孙",
        "eng": "kongcongzi",
        "chn": "孔丛子",
        "idx": "039",
        "txtlen": 35327,
        "dynacat": "先秦两汉",
        "school": "儒家",
        "srcDir": "../../ctext/main/dwnload/nodjsapp/out/ctext_res_clean",
        "srcFileType": ".htm",
        "srcFileNameKeyStr": "kongcongzi_"
    },
    "shenjian": {
        "url": "http://www.ctext.org/shenjian/zh",
        "dtv": "196",
        "dts": " [东汉] 196年-220年",
        "eng": "shenjian",
        "chn": "申鉴",
        "idx": "064",
        "txtlen": 10834,
        "dynacat": "先秦两汉",
        "school": "儒家",
        "srcDir": "../../ctext/main/dwnload/nodjsapp/out/ctext_res_clean",
        "srcFileType": ".htm",
        "srcFileNameKeyStr": "shenjian_"
    },
    "zhong-jing": {
        "url": "http://www.ctext.org/zhong-jing/zh",
        "dtv": "5",
        "dts": " [马融 东汉]东汉著名经古文学家",
        "eng": "zhong-jing",
        "chn": "忠经",
        "idx": "096",
        "txtlen": 4079,
        "dynacat": "先秦两汉",
        "school": "儒家",
        "srcDir": "../../ctext/main/dwnload/nodjsapp/out/ctext_res_clean",
        "srcFileType": ".htm",
        "srcFileNameKeyStr": "zhong-jing_"
    },
    "su-shu": {
        "url": "http://www.ctext.org/su-shu/zh",
        "dtv": "1000",
        "dts": " [成书年代, 宋](道家思想为宗旨，集儒、法、兵的思想发挥道的作用及功能)",
        "eng": "su-shu",
        "chn": "素书",
        "idx": "072",
        "txtlen": 1350,
        "dynacat": "先秦两汉",
        "school": "儒家/道家",
        "srcDir": "../../ctext/main/dwnload/nodjsapp/out/ctext_res_clean",
        "srcFileType": ".htm",
        "srcFileNameKeyStr": "su-shu_"
    },
    "xinyu": {
        "url": "http://www.ctext.org/xinyu/zh",
        "dtv": "-196",
        "dts": "[西汉] 公元前196年",
        "eng": "xinyu",
        "chn": "新语",
        "idx": "085",
        "txtlen": 9849,
        "dynacat": "先秦两汉",
        "school": "儒家",
        "srcDir": "../../ctext/main/dwnload/nodjsapp/out/ctext_res_clean",
        "srcFileType": ".htm",
        "srcFileNameKeyStr": "xinyu_"
    },
    "duduan": {
        "url": "http://www.ctext.org/duduan/zh",
        "dtv": "167",
        "dts": " [东汉 - 三国] 167年-258年",
        "eng": "duduan",
        "chn": "独断",
        "idx": "013",
        "txtlen": 9877,
        "dynacat": "先秦两汉",
        "school": "新语",
        "srcDir": "../../ctext/main/dwnload/nodjsapp/out/ctext_res_clean",
        "srcFileType": ".htm",
        "srcFileNameKeyStr": "duduan_"
    },
    "caizhong-langji": {
        "url": "http://www.ctext.org/caizhong-langji/zh",
        "dtv": "152",
        "dts": " [东汉] 152年-192年",
        "eng": "caizhong-langji",
        "chn": "蔡中郎集",
        "idx": "005",
        "txtlen": 59077,
        "dynacat": "先秦两汉",
        "school": "新语",
        "srcDir": "../../ctext/main/dwnload/nodjsapp/out/ctext_res_clean",
        "srcFileType": ".htm",
        "srcFileNameKeyStr": "caizhong-langji_"
    },
    "mozi": {
        "url": "http://www.ctext.org/mozi/zh",
        "dtv": "-490",
        "dts": " [春秋 - 战国] 公元前490年-公元前221年",
        "eng": "mozi",
        "chn": "墨子",
        "idx": "052",
        "txtlen": 80421,
        "dynacat": "先秦两汉",
        "school": "墨家",
        "srcDir": "../../ctext/main/dwnload/nodjsapp/out/ctext_res_clean",
        "srcFileType": ".htm",
        "srcFileNameKeyStr": "mozi_"
    },
    "mo-bian-zhu-xu": {
        "url": "http://www.ctext.org/mo-bian-zhu-xu/zh",
        "dtv": "265",
        "dts": " [西晋 (265年 - 317年)] 鲁胜著",
        "eng": "mo-bian-zhu-xu",
        "chn": "鲁胜墨辩注叙",
        "idx": "051",
        "txtlen": 292,
        "dynacat": "先秦两汉",
        "school": "墨家",
        "srcDir": "../../ctext/main/dwnload/nodjsapp/out/ctext_res_clean",
        "srcFileType": ".htm",
        "srcFileNameKeyStr": "mo-bian-zhu-xu_"
    },
    "zhuangzi": {
        "url": "http://www.ctext.org/zhuangzi/zh",
        "dtv": "-350",
        "dts": " [战国] 公元前350年-公元前250年",
        "eng": "zhuangzi",
        "chn": "庄子",
        "idx": "099",
        "txtlen": 65242,
        "dynacat": "先秦两汉",
        "school": "道家",
        "srcDir": "../../ctext/main/dwnload/nodjsapp/out/ctext_res_clean",
        "srcFileType": ".htm",
        "srcFileNameKeyStr": "zhuangzi_"
    },
    "dao-de-jing": {
        "url": "http://www.ctext.org/dao-de-jing/zh",
        "dtv": "-475",
        "dts": "[战国 (公元前475年 - 公元前221年)]",
        "eng": "dao-de-jing",
        "chn": "道德经",
        "idx": "010",
        "txtlen": 5278,
        "dynacat": "先秦两汉",
        "school": "道家",
        "srcDir": "../../ctext/main/dwnload/nodjsapp/out/ctext_res_clean",
        "srcFileType": ".htm",
        "srcFileNameKeyStr": "dao-de-jing_"
    },
    "liezi": {
        "url": "http://www.ctext.org/liezi/zh",
        "dtv": "-475",
        "dts": " [战国 (公元前475年 - 公元前221年)]",
        "eng": "liezi",
        "chn": "列子",
        "idx": "043",
        "txtlen": 30714,
        "dynacat": "先秦两汉",
        "school": "道家",
        "srcDir": "../../ctext/main/dwnload/nodjsapp/out/ctext_res_clean",
        "srcFileType": ".htm",
        "srcFileNameKeyStr": "liezi_"
    },
    "he-guan-zi": {
        "url": "http://www.ctext.org/he-guan-zi/zh",
        "dtv": "-475",
        "dts": " [战国 (公元前475年 - 公元前221年)]",
        "eng": "he-guan-zi",
        "chn": "鶡冠子",
        "idx": "029",
        "txtlen": 15845,
        "dynacat": "先秦两汉",
        "school": "道家",
        "srcDir": "../../ctext/main/dwnload/nodjsapp/out/ctext_res_clean",
        "srcFileType": ".htm",
        "srcFileNameKeyStr": "he-guan-zi_"
    },
    "wenzi": {
        "url": "http://www.ctext.org/wenzi/zh",
        "dtv": "212",
        "dts": "[东汉 - 晋] 212年-231年",
        "eng": "wenzi",
        "chn": "文子",
        "idx": "078",
        "txtlen": 39228,
        "dynacat": "先秦两汉",
        "school": "道家",
        "srcDir": "../../ctext/main/dwnload/nodjsapp/out/ctext_res_clean",
        "srcFileType": ".htm",
        "srcFileNameKeyStr": "wenzi_"
    },
    "wenshi-zhenjing": {
        "url": "http://www.ctext.org/wenshi-zhenjing/zh",
        "dtv": "1000",
        "dts": " [unknown]",
        "eng": "wenshi-zhenjing",
        "chn": "文始真经",
        "idx": "077",
        "txtlen": 11216,
        "dynacat": "先秦两汉",
        "school": "道家",
        "srcDir": "../../ctext/main/dwnload/nodjsapp/out/ctext_res_clean",
        "srcFileType": ".htm",
        "srcFileNameKeyStr": "wenshi-zhenjing_"
    },
    "lie-xian-zhuan": {
        "url": "http://www.ctext.org/lie-xian-zhuan/zh",
        "dtv": "-50",
        "dts": " [西汉] 公元前50年-8年",
        "eng": "lie-xian-zhuan",
        "chn": "列仙传",
        "idx": "042",
        "txtlen": 9385,
        "dynacat": "先秦两汉",
        "school": "道家",
        "srcDir": "../../ctext/main/dwnload/nodjsapp/out/ctext_res_clean",
        "srcFileType": ".htm",
        "srcFileNameKeyStr": "lie-xian-zhuan_"
    },
    "yuzi": {
        "url": "http://www.ctext.org/yuzi/zh",
        "dtv": "-300",
        "dts": " [战国]",
        "eng": "yuzi",
        "chn": "鬻子",
        "idx": "094",
        "txtlen": 1297,
        "dynacat": "先秦两汉",
        "school": "道家",
        "srcDir": "../../ctext/main/dwnload/nodjsapp/out/ctext_res_clean",
        "srcFileType": ".htm",
        "srcFileNameKeyStr": "yuzi_"
    },
    "heshanggong": {
        "url": "http://www.ctext.org/heshanggong/zh",
        "dtv": "-300",
        "dts": " [unknown]",
        "eng": "heshanggong",
        "chn": "老子河上公章句",
        "idx": "030",
        "txtlen": 20656,
        "dynacat": "先秦两汉",
        "school": "道家",
        "srcDir": "../../ctext/main/dwnload/nodjsapp/out/ctext_res_clean",
        "srcFileType": ".htm",
        "srcFileNameKeyStr": "heshanggong_"
    },
    "hanfeizi": {
        "url": "http://www.ctext.org/hanfeizi/zh",
        "dtv": "-475",
        "dts": " [战国 (公元前475年 - 公元前221年)]",
        "eng": "hanfeizi",
        "chn": "韩非子",
        "idx": "028",
        "txtlen": 106338,
        "dynacat": "先秦两汉",
        "school": "法家",
        "srcDir": "../../ctext/main/dwnload/nodjsapp/out/ctext_res_clean",
        "srcFileType": ".htm",
        "srcFileNameKeyStr": "hanfeizi_"
    },
    "shang-jun-shu": {
        "url": "http://www.ctext.org/shang-jun-shu/zh",
        "dtv": "-475",
        "dts": " [战国 (公元前475年 - 公元前221年)]",
        "eng": "shang-jun-shu",
        "chn": "商君书",
        "idx": "061",
        "txtlen": 20163,
        "dynacat": "先秦两汉",
        "school": "法家",
        "srcDir": "../../ctext/main/dwnload/nodjsapp/out/ctext_res_clean",
        "srcFileType": ".htm",
        "srcFileNameKeyStr": "shang-jun-shu_"
    },
    "shen-bu-hai": {
        "url": "http://www.ctext.org/shen-bu-hai/zh",
        "dtv": "-420",
        "dts": " [战国时代郑国]",
        "eng": "shen-bu-hai",
        "chn": "申不害",
        "idx": "063",
        "txtlen": 988,
        "dynacat": "先秦两汉",
        "school": "法家",
        "srcDir": "../../ctext/main/dwnload/nodjsapp/out/ctext_res_clean",
        "srcFileType": ".htm",
        "srcFileNameKeyStr": "shen-bu-hai_"
    },
    "shenzi": {
        "url": "http://www.ctext.org/shenzi/zh",
        "dtv": "-475",
        "dts": " [战国 (公元前475年 - 公元前221年)] 慎到著",
        "eng": "shenzi",
        "chn": "慎子",
        "idx": "065",
        "txtlen": 4239,
        "dynacat": "先秦两汉",
        "school": "法家",
        "srcDir": "../../ctext/main/dwnload/nodjsapp/out/ctext_res_clean",
        "srcFileType": ".htm",
        "srcFileNameKeyStr": "shenzi_"
    },
    "jian-zhu-ke-shu": {
        "url": "http://www.ctext.org/jian-zhu-ke-shu/zh",
        "dtv": "-237",
        "dts": " [战国] 公元前237年 李斯著",
        "eng": "jian-zhu-ke-shu",
        "chn": "谏逐客书",
        "idx": "034",
        "txtlen": 842,
        "dynacat": "先秦两汉",
        "school": "法家",
        "srcDir": "../../ctext/main/dwnload/nodjsapp/out/ctext_res_clean",
        "srcFileType": ".htm",
        "srcFileNameKeyStr": "jian-zhu-ke-shu_"
    },
    "guanzi": {
        "url": "http://www.ctext.org/guanzi/zh",
        "dtv": "-475",
        "dts": "[战国 - 汉 (公元前475年 - 220年)]",
        "eng": "guanzi",
        "chn": "管子",
        "idx": "020",
        "txtlen": 126627,
        "dynacat": "先秦两汉",
        "school": "法家",
        "srcDir": "../../ctext/main/dwnload/nodjsapp/out/ctext_res_clean",
        "srcFileType": ".htm",
        "srcFileNameKeyStr": "guanzi_"
    },
    "gongsunlongzi": {
        "url": "http://www.ctext.org/gongsunlongzi/zh",
        "dtv": "-475",
        "dts": " [战国 (公元前475年 - 公元前221年)]",
        "eng": "gongsunlongzi",
        "chn": "公孙龙子",
        "idx": "017",
        "txtlen": 3179,
        "dynacat": "先秦两汉",
        "school": "名家",
        "srcDir": "../../ctext/main/dwnload/nodjsapp/out/ctext_res_clean",
        "srcFileType": ".htm",
        "srcFileNameKeyStr": "gongsunlongzi_"
    },
    "art-of-war": {
        "url": "http://www.ctext.org/art-of-war/zh",
        "dtv": "-515",
        "dts": " [春秋] 公元前515年-公元前512年 孙武著",
        "eng": "art-of-war",
        "chn": "孙子兵法",
        "idx": "001",
        "txtlen": 6059,
        "dynacat": "先秦两汉",
        "school": "兵家",
        "srcDir": "../../ctext/main/dwnload/nodjsapp/out/ctext_res_clean",
        "srcFileType": ".htm",
        "srcFileNameKeyStr": "art-of-war_"
    },
    "wu-zi": {
        "url": "http://www.ctext.org/wu-zi/zh",
        "dtv": "-475",
        "dts": " [战国 (公元前475年 - 公元前221年)] 吴起著",
        "eng": "wu-zi",
        "chn": "吴子",
        "idx": "080",
        "txtlen": 4734,
        "dynacat": "先秦两汉",
        "school": "兵家",
        "srcDir": "../../ctext/main/dwnload/nodjsapp/out/ctext_res_clean",
        "srcFileType": ".htm",
        "srcFileNameKeyStr": "wu-zi_"
    },
    "liu-tao": {
        "url": "http://www.ctext.org/liu-tao/zh",
        "dtv": "-475",
        "dts": " [战国 (公元前475年 - 公元前221年)]",
        "eng": "liu-tao",
        "chn": "六韬",
        "idx": "045",
        "txtlen": 16838,
        "dynacat": "先秦两汉",
        "school": "兵家",
        "srcDir": "../../ctext/main/dwnload/nodjsapp/out/ctext_res_clean",
        "srcFileType": ".htm",
        "srcFileNameKeyStr": "liu-tao_"
    },
    "si-ma-fa": {
        "url": "http://www.ctext.org/si-ma-fa/zh",
        "dtv": "-772",
        "dts": " [春秋 - 战国 (公元前772年 - 公元前221年)]",
        "eng": "si-ma-fa",
        "chn": "司马法",
        "idx": "071",
        "txtlen": 3429,
        "dynacat": "先秦两汉",
        "school": "兵家",
        "srcDir": "../../ctext/main/dwnload/nodjsapp/out/ctext_res_clean",
        "srcFileType": ".htm",
        "srcFileNameKeyStr": "si-ma-fa_"
    },
    "wei-liao-zi": {
        "url": "http://www.ctext.org/wei-liao-zi/zh",
        "dtv": "-475",
        "dts": " [战国 (公元前475年 - 公元前221年)]",
        "eng": "wei-liao-zi",
        "chn": "尉缭子",
        "idx": "076",
        "txtlen": 9203,
        "dynacat": "先秦两汉",
        "school": "兵家",
        "srcDir": "../../ctext/main/dwnload/nodjsapp/out/ctext_res_clean",
        "srcFileType": ".htm",
        "srcFileNameKeyStr": "wei-liao-zi_"
    },
    "three-strategies": {
        "url": "http://www.ctext.org/three-strategies/zh",
        "dtv": "-100",
        "dts": " [西汉] 公元前100年-9年",
        "eng": "three-strategies",
        "chn": "三略",
        "idx": "075",
        "txtlen": 3816,
        "dynacat": "先秦两汉",
        "school": "兵家",
        "srcDir": "../../ctext/main/dwnload/nodjsapp/out/ctext_res_clean",
        "srcFileType": ".htm",
        "srcFileNameKeyStr": "three-strategies_"
    },
    "hai-dao-suan-jing": {
        "url": "http://www.ctext.org/hai-dao-suan-jing/zh",
        "dtv": "263",
        "dts": " [三国] 263年",
        "eng": "hai-dao-suan-jing",
        "chn": "海岛算经",
        "idx": "025",
        "txtlen": 1521,
        "dynacat": "先秦两汉",
        "school": "算书",
        "srcDir": "../../ctext/main/dwnload/nodjsapp/out/ctext_res_clean",
        "srcFileType": ".htm",
        "srcFileNameKeyStr": "hai-dao-suan-jing_"
    },
    "nine-chapters": {
        "url": "http://www.ctext.org/nine-chapters/zh",
        "dtv": "-120",
        "dts": " [西汉 - 新] 公元前120年-20年",
        "eng": "nine-chapters",
        "chn": "九章算术",
        "idx": "055",
        "txtlen": 20315,
        "dynacat": "先秦两汉",
        "school": "算书",
        "srcDir": "../../ctext/main/dwnload/nodjsapp/out/ctext_res_clean",
        "srcFileType": ".htm",
        "srcFileNameKeyStr": "nine-chapters_"
    },
    "sunzi-suan-jing": {
        "url": "http://www.ctext.org/sunzi-suan-jing/zh",
        "dtv": "420",
        "dts": " [南北朝 (420年 - 581年)]",
        "eng": "sunzi-suan-jing",
        "chn": "孙子算经",
        "idx": "073",
        "txtlen": 9673,
        "dynacat": "先秦两汉",
        "school": "算书",
        "srcDir": "../../ctext/main/dwnload/nodjsapp/out/ctext_res_clean",
        "srcFileType": ".htm",
        "srcFileNameKeyStr": "sunzi-suan-jing_"
    },
    "zhou-bi-suan-jing": {
        "url": "http://www.ctext.org/zhou-bi-suan-jing/zh",
        "dtv": "-50",
        "dts": " [汉] 公元前50年-100年",
        "eng": "zhou-bi-suan-jing",
        "chn": "周髀算经",
        "idx": "098",
        "txtlen": 6484,
        "dynacat": "先秦两汉",
        "school": "算书",
        "srcDir": "../../ctext/main/dwnload/nodjsapp/out/ctext_res_clean",
        "srcFileType": ".htm",
        "srcFileNameKeyStr": "zhou-bi-suan-jing_"
    },
    "huainanzi": {
        "url": "http://www.ctext.org/huainanzi/zh",
        "dtv": "-206",
        "dts": " [西汉 (公元前206年 - 9年)]",
        "eng": "huainanzi",
        "chn": "淮南子",
        "idx": "032",
        "txtlen": 130806,
        "dynacat": "先秦两汉",
        "school": "杂家",
        "srcDir": "../../ctext/main/dwnload/nodjsapp/out/ctext_res_clean",
        "srcFileType": ".htm",
        "srcFileNameKeyStr": "huainanzi_"
    },
    "lv-shi-chun-qiu": {
        "url": "http://www.ctext.org/lv-shi-chun-qiu/zh",
        "dtv": "-247",
        "dts": "[战国] 公元前247年-公元前239年 吕不韦著",
        "eng": "lv-shi-chun-qiu",
        "chn": "吕氏春秋",
        "idx": "048",
        "txtlen": 100865,
        "dynacat": "先秦两汉",
        "school": "杂家",
        "srcDir": "../../ctext/main/dwnload/nodjsapp/out/ctext_res_clean",
        "srcFileType": ".htm",
        "srcFileNameKeyStr": "lv-shi-chun-qiu_"
    },
    "gui-gu-zi": {
        "url": "http://www.ctext.org/gui-gu-zi/zh",
        "dtv": "-475",
        "dts": " [战国 (公元前475年 - 公元前221年)]",
        "eng": "gui-gu-zi",
        "chn": "鬼谷子",
        "idx": "021",
        "txtlen": 7987,
        "dynacat": "先秦两汉",
        "school": "杂家",
        "srcDir": "../../ctext/main/dwnload/nodjsapp/out/ctext_res_clean",
        "srcFileType": ".htm",
        "srcFileNameKeyStr": "gui-gu-zi_"
    },
    "yin-wen-zi": {
        "url": "http://www.ctext.org/yin-wen-zi/zh",
        "dtv": "-300",
        "dts": " [战国]",
        "eng": "yin-wen-zi",
        "chn": "尹文子",
        "idx": "092",
        "txtlen": 6223,
        "dynacat": "先秦两汉",
        "school": "杂家",
        "srcDir": "../../ctext/main/dwnload/nodjsapp/out/ctext_res_clean",
        "srcFileType": ".htm",
        "srcFileNameKeyStr": "yin-wen-zi_"
    },
    "deng-xi-zi": {
        "url": "http://www.ctext.org/deng-xi-zi/zh",
        "dtv": "-545",
        "dts": " [郑国大夫，春秋末期思想家]",
        "eng": "deng-xi-zi",
        "chn": "邓析子",
        "idx": "011",
        "txtlen": 3132,
        "dynacat": "先秦两汉",
        "school": "杂家",
        "srcDir": "../../ctext/main/dwnload/nodjsapp/out/ctext_res_clean",
        "srcFileType": ".htm",
        "srcFileNameKeyStr": "deng-xi-zi_"
    },
    "shiji": {
        "url": "http://www.ctext.org/shiji/zh",
        "dtv": "-109",
        "dts": " [西汉] 公元前109年-公元前91年 司马迁著",
        "eng": "shiji",
        "chn": "史记",
        "idx": "067",
        "txtlen": 504758,
        "dynacat": "先秦两汉",
        "school": "史书",
        "srcDir": "../../ctext/main/dwnload/nodjsapp/out/ctext_res_clean",
        "srcFileType": ".htm",
        "srcFileNameKeyStr": "shiji_"
    },
    "chun-qiu-zuo-zhuan": {
        "url": "http://www.ctext.org/chun-qiu-zuo-zhuan/zh",
        "dtv": "-468",
        "dts": " [战国] 公元前468年-公元前300年",
        "eng": "chun-qiu-zuo-zhuan",
        "chn": "春秋左传",
        "idx": "008",
        "txtlen": 197834,
        "dynacat": "先秦两汉",
        "school": "史书",
        "srcDir": "../../ctext/main/dwnload/nodjsapp/out/ctext_res_clean",
        "srcFileType": ".htm",
        "srcFileNameKeyStr": "chun-qiu-zuo-zhuan_"
    },
    "lost-book-of-zhou": {
        "url": "http://www.ctext.org/lost-book-of-zhou/zh",
        "dtv": "-475",
        "dts": "[战国 (公元前475年 - 公元前221年)]",
        "eng": "lost-book-of-zhou",
        "chn": "逸周书",
        "idx": "046",
        "txtlen": 31150,
        "dynacat": "先秦两汉",
        "school": "史书",
        "srcDir": "../../ctext/main/dwnload/nodjsapp/out/ctext_res_clean",
        "srcFileType": ".htm",
        "srcFileNameKeyStr": "lost-book-of-zhou_"
    },
    "guo-yu": {
        "url": "http://www.ctext.org/guo-yu/zh",
        "dtv": "-475",
        "dts": "[战国 (公元前475年 - 公元前221年)]",
        "eng": "guo-yu",
        "chn": "国语",
        "idx": "023",
        "txtlen": 70441,
        "dynacat": "先秦两汉",
        "school": "史书",
        "srcDir": "../../ctext/main/dwnload/nodjsapp/out/ctext_res_clean",
        "srcFileType": ".htm",
        "srcFileNameKeyStr": "guo-yu_"
    },
    "yanzi-chun-qiu": {
        "url": "http://www.ctext.org/yanzi-chun-qiu/zh",
        "dtv": "-475",
        "dts": " [战国 (公元前475年 - 公元前221年)]",
        "eng": "yanzi-chun-qiu",
        "chn": "晏子春秋",
        "idx": "090",
        "txtlen": 43465,
        "dynacat": "先秦两汉",
        "school": "史书",
        "srcDir": "../../ctext/main/dwnload/nodjsapp/out/ctext_res_clean",
        "srcFileType": ".htm",
        "srcFileNameKeyStr": "yanzi-chun-qiu_"
    },
    "wu-yue-chun-qiu": {
        "url": "http://www.ctext.org/wu-yue-chun-qiu/zh",
        "dtv": "-550",
        "dts": " [东汉] 50年-100年, 东汉 赵晔 撰，是一部记述春秋战国时期吴、越两国史事为主的史学著作",
        "eng": "wu-yue-chun-qiu",
        "chn": "吴越春秋",
        "idx": "079",
        "txtlen": 39350,
        "dynacat": "先秦两汉",
        "school": "史书",
        "srcDir": "../../ctext/main/dwnload/nodjsapp/out/ctext_res_clean",
        "srcFileType": ".htm",
        "srcFileNameKeyStr": "wu-yue-chun-qiu_"
    },
    "yue-jue-shu": {
        "url": "http://www.ctext.org/yue-jue-shu/zh",
        "dtv": "-250",
        "dts": " [东汉] 50年-70年, 作者:吴平 东汉. 不仅是浙江最早的地方志，也是国内现存最古的地方志。此书还保存了先秦时期许多珍贵的思想史资料。历代的抄本、刻本有翻元本",
        "eng": "yue-jue-shu",
        "chn": "越绝书",
        "idx": "093",
        "txtlen": 30826,
        "dynacat": "先秦两汉",
        "school": "史书",
        "srcDir": "../../ctext/main/dwnload/nodjsapp/out/ctext_res_clean",
        "srcFileType": ".htm",
        "srcFileNameKeyStr": "yue-jue-shu_"
    },
    "zhan-guo-ce": {
        "url": "http://www.ctext.org/zhan-guo-ce/zh",
        "dtv": "-350",
        "dts": " [战国 - 西汉] 公元前350年-公元前6年",
        "eng": "zhan-guo-ce",
        "chn": "战国策",
        "idx": "095",
        "txtlen": 124711,
        "dynacat": "先秦两汉",
        "school": "史书",
        "srcDir": "../../ctext/main/dwnload/nodjsapp/out/ctext_res_clean",
        "srcFileType": ".htm",
        "srcFileNameKeyStr": "zhan-guo-ce_"
    },
    "yan-tie-lun": {
        "url": "http://www.ctext.org/yan-tie-lun/zh",
        "dtv": "-81",
        "dts": "[西汉] 公元前81年-9年 桓宽著",
        "eng": "yan-tie-lun",
        "chn": "盐铁论",
        "idx": "087",
        "txtlen": 49676,
        "dynacat": "先秦两汉",
        "school": "史书",
        "srcDir": "../../ctext/main/dwnload/nodjsapp/out/ctext_res_clean",
        "srcFileType": ".htm",
        "srcFileNameKeyStr": "yan-tie-lun_"
    },
    "lie-nv-zhuan": {
        "url": "http://www.ctext.org/lie-nv-zhuan/zh",
        "dtv": "-206",
        "dts": " [西汉 (公元前206年 - 9年)] 刘向著",
        "eng": "lie-nv-zhuan",
        "chn": "列女传",
        "idx": "041",
        "txtlen": 45384,
        "dynacat": "先秦两汉",
        "school": "史书",
        "srcDir": "../../ctext/main/dwnload/nodjsapp/out/ctext_res_clean",
        "srcFileType": ".htm",
        "srcFileNameKeyStr": "lie-nv-zhuan_"
    },
    "guliang-zhuan": {
        "url": "http://www.ctext.org/guliang-zhuan/zh",
        "dtv": "-206",
        "dts": "[西汉 (公元前206年 - 9年)]",
        "eng": "guliang-zhuan",
        "chn": "春秋穀梁传",
        "idx": "022",
        "txtlen": 41995,
        "dynacat": "先秦两汉",
        "school": "史书",
        "srcDir": "../../ctext/main/dwnload/nodjsapp/out/ctext_res_clean",
        "srcFileType": ".htm",
        "srcFileNameKeyStr": "guliang-zhuan_"
    },
    "gongyang-zhuan": {
        "url": "http://www.ctext.org/gongyang-zhuan/zh",
        "dtv": "-206",
        "dts": " [西汉 (公元前206年 - 9年)]",
        "eng": "gongyang-zhuan",
        "chn": "春秋公羊传",
        "idx": "018",
        "txtlen": 45503,
        "dynacat": "先秦两汉",
        "school": "史书",
        "srcDir": "../../ctext/main/dwnload/nodjsapp/out/ctext_res_clean",
        "srcFileType": ".htm",
        "srcFileNameKeyStr": "gongyang-zhuan_"
    },
    "han-shu": {
        "url": "http://www.ctext.org/han-shu/zh",
        "dtv": "36",
        "dts": " [新 - 东汉] 36年-111年",
        "eng": "han-shu",
        "chn": "汉书",
        "idx": "027",
        "txtlen": 722834,
        "dynacat": "先秦两汉",
        "school": "史书",
        "srcDir": "../../ctext/main/dwnload/nodjsapp/out/ctext_res_clean",
        "srcFileType": ".htm",
        "srcFileNameKeyStr": "han-shu_"
    },
    "qian-han-ji": {
        "url": "http://www.ctext.org/qian-han-ji/zh",
        "dtv": "198",
        "dts": " [东汉] 198年-200年",
        "eng": "qian-han-ji",
        "chn": "前汉纪",
        "idx": "057",
        "txtlen": 178608,
        "dynacat": "先秦两汉",
        "school": "史书",
        "srcDir": "../../ctext/main/dwnload/nodjsapp/out/ctext_res_clean",
        "srcFileType": ".htm",
        "srcFileNameKeyStr": "qian-han-ji_"
    },
    "dong-guan-han-ji": {
        "url": "http://www.ctext.org/dong-guan-han-ji/zh",
        "dtv": "-5",
        "dts": " [东汉] 60年-160年. 东汉光武帝刘秀（公元前5年1月15日－57年3月29日）",
        "eng": "dong-guan-han-ji",
        "chn": "东观汉记",
        "idx": "012",
        "txtlen": 79575,
        "dynacat": "先秦两汉",
        "school": "史书",
        "srcDir": "../../ctext/main/dwnload/nodjsapp/out/ctext_res_clean",
        "srcFileType": ".htm",
        "srcFileNameKeyStr": "dong-guan-han-ji_"
    },
    "hou-han-shu": {
        "url": "http://www.ctext.org/hou-han-shu/zh",
        "dtv": "420",
        "dts": " [南北朝] 420年-445年",
        "eng": "hou-han-shu",
        "chn": "后汉书",
        "idx": "031",
        "txtlen": 680904,
        "dynacat": "先秦两汉",
        "school": "史书",
        "srcDir": "../../ctext/main/dwnload/nodjsapp/out/ctext_res_clean",
        "srcFileType": ".htm",
        "srcFileNameKeyStr": "hou-han-shu_"
    },
    "zhushu-jinian": {
        "url": "http://www.ctext.org/zhushu-jinian/zh",
        "dtv": "-475",
        "dts": " [战国 (公元前475年 - 公元前221年)]",
        "eng": "zhushu-jinian",
        "chn": "竹书纪年",
        "idx": "100",
        "txtlen": 9340,
        "dynacat": "先秦两汉",
        "school": "史书",
        "srcDir": "../../ctext/main/dwnload/nodjsapp/out/ctext_res_clean",
        "srcFileType": ".htm",
        "srcFileNameKeyStr": "zhushu-jinian_"
    },
    "mutianzi-zhuan": {
        "url": "http://www.ctext.org/mutianzi-zhuan/zh",
        "dtv": "-370",
        "dts": " [战国] 公元前370年-公元前330年",
        "eng": "mutianzi-zhuan",
        "chn": "穆天子传",
        "idx": "053",
        "txtlen": 6818,
        "dynacat": "先秦两汉",
        "school": "史书",
        "srcDir": "../../ctext/main/dwnload/nodjsapp/out/ctext_res_clean",
        "srcFileType": ".htm",
        "srcFileNameKeyStr": "mutianzi-zhuan_"
    },
    "gu-san-fen": {
        "url": "http://www.ctext.org/gu-san-fen/zh",
        "dtv": "-206",
        "dts": "[汉 (公元前206年 - 220年)]",
        "eng": "gu-san-fen",
        "chn": "古三坟",
        "idx": "019",
        "txtlen": 4999,
        "dynacat": "先秦两汉",
        "school": "史书",
        "srcDir": "../../ctext/main/dwnload/nodjsapp/out/ctext_res_clean",
        "srcFileType": ".htm",
        "srcFileNameKeyStr": "gu-san-fen_"
    },
    "yandanzi": {
        "url": "http://www.ctext.org/yandanzi/zh",
        "dtv": "-200",
        "dts": "[秦汉之间]",
        "eng": "yandanzi",
        "chn": "燕丹子",
        "idx": "088",
        "txtlen": 2727,
        "dynacat": "先秦两汉",
        "school": "史书",
        "srcDir": "../../ctext/main/dwnload/nodjsapp/out/ctext_res_clean",
        "srcFileType": ".htm",
        "srcFileNameKeyStr": "yandanzi_"
    },
    "xijing-zaji": {
        "url": "http://www.ctext.org/xijing-zaji/zh",
        "dtv": "-100",
        "dts": "[汉]",
        "eng": "xijing-zaji",
        "chn": "西京杂记",
        "idx": "082",
        "txtlen": 13493,
        "dynacat": "先秦两汉",
        "school": "史书",
        "srcDir": "../../ctext/main/dwnload/nodjsapp/out/ctext_res_clean",
        "srcFileType": ".htm",
        "srcFileNameKeyStr": "xijing-zaji_"
    },
    "book-of-poetry": {
        "url": "http://www.ctext.org/book-of-poetry/zh",
        "dtv": "-1000",
        "dts": "[西周 (公元前1046年 - 公元前771年)]",
        "eng": "book-of-poetry",
        "chn": "诗经",
        "idx": "004",
        "txtlen": 30497,
        "dynacat": "先秦两汉",
        "school": "经典文献",
        "srcDir": "../../ctext/main/dwnload/nodjsapp/out/ctext_res_clean",
        "srcFileType": ".htm",
        "srcFileNameKeyStr": "book-of-poetry_"
    },
    "shang-shu": {
        "url": "http://www.ctext.org/shang-shu/zh",
        "dtv": "-772",
        "dts": " [春秋 (公元前772年 - 公元前476年)]",
        "eng": "shang-shu",
        "chn": "尚书",
        "idx": "062",
        "txtlen": 25796,
        "dynacat": "先秦两汉",
        "school": "经典文献",
        "srcDir": "../../ctext/main/dwnload/nodjsapp/out/ctext_res_clean",
        "srcFileType": ".htm",
        "srcFileNameKeyStr": "shang-shu_"
    },
    "book-of-changes": {
        "url": "http://www.ctext.org/book-of-changes/zh",
        "dtv": "-1000",
        "dts": "[西周 (公元前1046年 - 公元前771年)]",
        "eng": "book-of-changes",
        "chn": "周易",
        "idx": "003",
        "txtlen": 28745,
        "dynacat": "先秦两汉",
        "school": "经典文献",
        "srcDir": "../../ctext/main/dwnload/nodjsapp/out/ctext_res_clean",
        "srcFileType": ".htm",
        "srcFileNameKeyStr": "book-of-changes_"
    },
    "rites-of-zhou": {
        "url": "http://www.ctext.org/rites-of-zhou/zh",
        "dtv": "-300",
        "dts": "[战国] 公元前300年-公元前100年",
        "eng": "rites-of-zhou",
        "chn": "周礼",
        "idx": "058",
        "txtlen": 49420,
        "dynacat": "先秦两汉",
        "school": "经典文献",
        "srcDir": "../../ctext/main/dwnload/nodjsapp/out/ctext_res_clean",
        "srcFileType": ".htm",
        "srcFileNameKeyStr": "rites-of-zhou_"
    },
    "chu-ci": {
        "url": "http://www.ctext.org/chu-ci/zh",
        "dtv": "-475",
        "dts": "[战国 (公元前475年 - 公元前221年)]",
        "eng": "chu-ci",
        "chn": "楚辞",
        "idx": "006",
        "txtlen": 27112,
        "dynacat": "先秦两汉",
        "school": "经典文献",
        "srcDir": "../../ctext/main/dwnload/nodjsapp/out/ctext_res_clean",
        "srcFileType": ".htm",
        "srcFileNameKeyStr": "chu-ci_"
    },
    "yili": {
        "url": "http://www.ctext.org/yili/zh",
        "dtv": "-475",
        "dts": " [战国 (公元前475年 - 公元前221年)]",
        "eng": "yili",
        "chn": "仪礼",
        "idx": "091",
        "txtlen": 53917,
        "dynacat": "先秦两汉",
        "school": "经典文献",
        "srcDir": "../../ctext/main/dwnload/nodjsapp/out/ctext_res_clean",
        "srcFileType": ".htm",
        "srcFileNameKeyStr": "yili_"
    },
    "shan-hai-jing": {
        "url": "http://www.ctext.org/shan-hai-jing/zh",
        "dtv": "-475",
        "dts": "[战国 - 汉 (公元前475年 - 220年)]",
        "eng": "shan-hai-jing",
        "chn": "山海经",
        "idx": "059",
        "txtlen": 31232,
        "dynacat": "先秦两汉",
        "school": "经典文献",
        "srcDir": "../../ctext/main/dwnload/nodjsapp/out/ctext_res_clean",
        "srcFileType": ".htm",
        "srcFileNameKeyStr": "shan-hai-jing_"
    },
    "jiaoshi-yilin": {
        "url": "http://www.ctext.org/jiaoshi-yilin/zh",
        "dtv": "-206",
        "dts": " [汉 (公元前206年 - 220年)] 焦延寿著",
        "eng": "jiaoshi-yilin",
        "chn": "焦氏易林",
        "idx": "035",
        "txtlen": 75311,
        "dynacat": "先秦两汉",
        "school": "经典文献",
        "srcDir": "../../ctext/main/dwnload/nodjsapp/out/ctext_res_clean",
        "srcFileType": ".htm",
        "srcFileNameKeyStr": "jiaoshi-yilin_"
    },
    "jingshi-yizhuan": {
        "url": "http://www.ctext.org/jingshi-yizhuan/zh",
        "dtv": "-57",
        "dts": " [西汉] 公元前57年-公元前37年 京房著",
        "eng": "jingshi-yizhuan",
        "chn": "京氏易传",
        "idx": "037",
        "txtlen": 13463,
        "dynacat": "先秦两汉",
        "school": "经典文献",
        "srcDir": "../../ctext/main/dwnload/nodjsapp/out/ctext_res_clean",
        "srcFileType": ".htm",
        "srcFileNameKeyStr": "jingshi-yizhuan_"
    },
    "shishuo": {
        "url": "http://www.ctext.org/shishuo/zh",
        "dtv": 1100,
        "dts": " [北宋]",
        "eng": "shishuo",
        "chn": "诗说",
        "idx": "068",
        "txtlen": 6663,
        "dynacat": "先秦两汉",
        "school": "经典文献",
        "srcDir": "../../ctext/main/dwnload/nodjsapp/out/ctext_res_clean",
        "srcFileType": ".htm",
        "srcFileNameKeyStr": "shishuo_"
    },
    "shuo-wen-jie-zi": {
        "url": "http://www.ctext.org/shuo-wen-jie-zi/zh",
        "dtv": "100",
        "dts": "[东汉] 100年-121年 许慎著",
        "eng": "shuo-wen-jie-zi",
        "chn": "说文解字",
        "idx": "069",
        "txtlen": 117528,
        "dynacat": "先秦两汉",
        "school": "字书",
        "srcDir": "../../ctext/main/dwnload/nodjsapp/out/ctext_res_clean",
        "srcFileType": ".htm",
        "srcFileNameKeyStr": "shuo-wen-jie-zi_"
    },
    "er-ya": {
        "url": "http://www.ctext.org/er-ya/zh",
        "dtv": "-221",
        "dts": " [秦 - 西汉 (公元前221年 - 9年)]",
        "eng": "er-ya",
        "chn": "尔雅",
        "idx": "014",
        "txtlen": 10368,
        "dynacat": "先秦两汉",
        "school": "字书",
        "srcDir": "../../ctext/main/dwnload/nodjsapp/out/ctext_res_clean",
        "srcFileType": ".htm",
        "srcFileNameKeyStr": "014_er-ya_"
    },
    "shi-ming": {
        "url": "http://www.ctext.org/shi-ming/zh",
        "dtv": "190",
        "dts": " [东汉] 190年-210年",
        "eng": "shi-ming",
        "chn": "释名",
        "idx": "066",
        "txtlen": 21508,
        "dynacat": "先秦两汉",
        "school": "字书",
        "srcDir": "../../ctext/main/dwnload/nodjsapp/out/ctext_res_clean",
        "srcFileType": ".htm",
        "srcFileNameKeyStr": "shi-ming_"
    },
    "fang-yan": {
        "url": "http://www.ctext.org/fang-yan/zh",
        "dtv": "-206",
        "dts": " [西汉 (公元前206年 - 9年)] 杨雄著",
        "eng": "fang-yan",
        "chn": "方言",
        "idx": "015",
        "txtlen": 12077,
        "dynacat": "先秦两汉",
        "school": "字书",
        "srcDir": "../../ctext/main/dwnload/nodjsapp/out/ctext_res_clean",
        "srcFileType": ".htm",
        "srcFileNameKeyStr": "fang-yan_"
    },
    "jijiupian": {
        "url": "http://www.ctext.org/jijiupian/zh",
        "dtv": "-48",
        "dts": " [西汉] 公元前48年-公元前33年",
        "eng": "jijiupian",
        "chn": "急就篇",
        "idx": "036",
        "txtlen": 2016,
        "dynacat": "先秦两汉",
        "school": "字书",
        "srcDir": "../../ctext/main/dwnload/nodjsapp/out/ctext_res_clean",
        "srcFileType": ".htm",
        "srcFileNameKeyStr": "jijiupian_"
    },
    "huangdi-neijing": {
        "url": "http://www.ctext.org/huangdi-neijing/zh",
        "dtv": "-475",
        "dts": " [战国 - 西汉 (公元前475年 - 9年)]",
        "eng": "huangdi-neijing",
        "chn": "黄帝内经",
        "idx": "033",
        "txtlen": 153806,
        "dynacat": "先秦两汉",
        "school": "医学",
        "srcDir": "../../ctext/main/dwnload/nodjsapp/out/ctext_res_clean",
        "srcFileType": ".htm",
        "srcFileNameKeyStr": "huangdi-neijing_"
    },
    "nan-jing": {
        "url": "http://www.ctext.org/nan-jing/zh",
        "dtv": "-206",
        "dts": " [汉 (公元前206年 - 220年)]",
        "eng": "nan-jing",
        "chn": "难经",
        "idx": "054",
        "txtlen": 11983,
        "dynacat": "先秦两汉",
        "school": "医学",
        "srcDir": "../../ctext/main/dwnload/nodjsapp/out/ctext_res_clean",
        "srcFileType": ".htm",
        "srcFileNameKeyStr": "nan-jing_"
    },
    "shang-han-lun": {
        "url": "http://www.ctext.org/shang-han-lun/zh",
        "dtv": "25",
        "dts": " [东汉 (25年 - 220年)]",
        "eng": "shang-han-lun",
        "chn": "伤寒论",
        "idx": "060",
        "txtlen": 31606,
        "dynacat": "先秦两汉",
        "school": "医学",
        "srcDir": "../../ctext/main/dwnload/nodjsapp/out/ctext_res_clean",
        "srcFileType": ".htm",
        "srcFileNameKeyStr": "shang-han-lun_"
    },
    "jinkui-yaolue": {
        "url": "http://www.ctext.org/jinkui-yaolue/zh",
        "dtv": "170",
        "dts": "[东汉] 170年-219年",
        "eng": "jinkui-yaolue",
        "chn": "金匮要略",
        "idx": "038",
        "txtlen": 28758,
        "dynacat": "先秦两汉",
        "school": "医学",
        "srcDir": "../../ctext/main/dwnload/nodjsapp/out/ctext_res_clean",
        "srcFileType": ".htm",
        "srcFileNameKeyStr": "jinkui-yaolue_"
    },
    "guodian": {
        "url": "http://www.ctext.org/guodian/zh",
        "dtv": "-250",
        "dts": "-250",
        "eng": "guodian",
        "chn": "郭店",
        "idx": "024",
        "txtlen": 1829,
        "dynacat": "先秦两汉",
        "school": "出土文献",
        "srcDir": "../../ctext/main/dwnload/nodjsapp/out/ctext_res_clean",
        "srcFileType": ".htm",
        "srcFileNameKeyStr": "guodian_"
    },
    "mawangdui": {
        "url": "http://www.ctext.org/mawangdui/zh",
        "dtv": "-168",
        "dts": "-168",
        "eng": "mawangdui",
        "chn": "马王堆",
        "idx": "049",
        "txtlen": 10864,
        "dynacat": "先秦两汉",
        "school": "出土文献",
        "srcDir": "../../ctext/main/dwnload/nodjsapp/out/ctext_res_clean",
        "srcFileType": ".htm",
        "srcFileNameKeyStr": "mawangdui_"
    },
    "dao-de-zhen-jing-zhu": {
        "eng": "dao-de-zhen-jing-zhu",
        "dtv": "220",
        "dts": "220",
        "chn": "道德真经注",
        "txtlen": 17071,
        "srcDir": "../../ctext_postHan/0_WeiJinNanBeiChao/Dao4_De2_Zhen1_Jing1_Zhu4/dwn_files/",
        "srcFileType": ".txt",
        "dynacat": "汉代之后",
        "school": "魏晋南北朝"
    },
    "shi-shuo-xin-yu": {
        "eng": "shi-shuo-xin-yu",
        "dtv": "420",
        "dts": "420",
        "chn": "世说新语",
        "txtlen": 61065,
        "srcDir": "../../ctext_postHan/0_WeiJinNanBeiChao/Shi4_Shuo1_Xin1_Yu3/dwn_files/",
        "srcFileType": ".txt",
        "dynacat": "汉代之后",
        "school": "魏晋南北朝"
    },
    "yan-shi-jia-xun": {
        "eng": "yan-shi-jia-xun",
        "dtv": "420",
        "dts": "420",
        "chn": "颜氏家训",
        "txtlen": 33019,
        "srcDir": "../../ctext_postHan/0_WeiJinNanBeiChao/Yan2_Shi4_Jia1_Xun4/dwn_files/",
        "srcFileType": ".txt",
        "dynacat": "汉代之后",
        "school": "魏晋南北朝"
    },
    "wenxin-diaolong": {
        "eng": "wenxin-diaolong",
        "dtv": "485",
        "dts": "485",
        "chn": "文心雕龙",
        "txtlen": 37958,
        "srcDir": "../../ctext_postHan/0_WeiJinNanBeiChao/WenXin_DiaoLong/dwn_files/",
        "srcFileType": ".txt",
        "dynacat": "汉代之后",
        "school": "魏晋南北朝"
    },
    "baopuzi": {
        "eng": "baopuzi",
        "dtv": "300",
        "dts": "300",
        "chn": "抱朴子",
        "txtlen": 154591,
        "srcDir": "../../ctext_postHan/0_WeiJinNanBeiChao/Bao1_Pu2_Zi3/dwn_files/",
        "srcFileType": ".txt",
        "dynacat": "汉代之后",
        "school": "魏晋南北朝"
    },
    "shui-jing-zhu": {
        "eng": "shui-jing-zhu",
        "dtv": "500",
        "dts": "386年—534年 北魏晚期的郦道元",
        "chn": "水经注",
        "txtlen": "312679",
        "srcDir": "../../ctext_postHan/0_WeiJinNanBeiChao/Shui3_Jing1_Zhu4/dwn_files/",
        "srcFileType": ".txt",
        "dynacat": "汉代之后",
        "school": "魏晋南北朝"
    },
    "Gao1_Shi4_Zhuan4": {
        "eng": "gao-shi-zhuan",
        "dtv": "400",
        "dts": "西晋(公元265-316年) 东晋(公元317-420年) 晋皇甫谧撰。谧字士安，自号玄晏先生，安定朝那人，汉太尉嵩之曾孙。",
        "chn": "高士传",
        "txtlen": "17532",
        "srcDir": "../../ctext_postHan/0_WeiJinNanBeiChao/Gao1_Shi4_Zhuan4/dwn_files/",
        "srcFileType": ".txt",
        "dynacat": "汉代之后",
        "school": "魏晋南北朝"
    },
    "Shen2_Yi4_Jing1": {
        "eng": "gao-shi-zhuan",
        "dtv": "25",
        "dts": "25 成书于汉代",
        "chn": "神异经",
        "txtlen": "3111",
        "srcDir": "../../ctext_postHan/0_WeiJinNanBeiChao/Shen2_Yi4_Jing1/dwn_files/",
        "srcFileType": ".txt",
        "dynacat": "汉代之后",
        "school": "魏晋南北朝"
    },
    "Han4_Wu3_Dong4_Ming2_Ji4": {
        "eng": "gao-shi-zhuan",
        "dtv": "25",
        "dts": "25 东汉时代的志怪笔记，全名《汉武洞冥记》",
        "chn": "洞冥记",
        "txtlen": "5313",
        "srcDir": "../../ctext_postHan/0_WeiJinNanBeiChao/Han4_Wu3_Dong4_Ming2_Ji4/dwn_files/",
        "srcFileType": ".txt",
        "dynacat": "汉代之后",
        "school": "魏晋南北朝"
    },
    "renwuzhi": {
        "eng": "renwuzhi",
        "dtv": "190",
        "dts": "190",
        "chn": "人物志",
        "txtlen": 11677,
        "srcDir": "../../ctext_postHan/0_WeiJinNanBeiChao/Ren2_Wu4_Zhi4/dwn_files/",
        "srcFileType": ".txt",
        "dynacat": "汉代之后",
        "school": "魏晋南北朝"
    },
    "jinlouzi": {
        "eng": "jinlouzi",
        "dtv": "554",
        "dts": "554",
        "chn": "金楼子",
        "txtlen": 47227,
        "srcDir": "../../ctext_postHan/0_WeiJinNanBeiChao/Jin1_Lou2_Zi3/dwn_files/",
        "srcFileType": ".txt",
        "dynacat": "汉代之后",
        "school": "魏晋南北朝"
    },
    "sanguozhi": {
        "eng": "sanguozhi",
        "dtv": "265",
        "dts": "265",
        "chn": "三国志",
        "txtlen": 690253,
        "srcDir": "../../ctext_postHan/SanGuoZhi265/dwnfiles/",
        "srcFileType": ".txt",
        "dynacat": "汉代之后",
        "school": "魏晋南北朝"
    },
    "qunshu-zhiyao": {
        "eng": "qunshu-zhiyao",
        "dtv": "631",
        "dts": "631",
        "chn": "群书治要",
        "txtlen": 438074,
        "srcDir": "../../ctext_postHan/1_Shui2Tang2/Qun2_Shu1_Zhi4_Yao4/dwn_files/",
        "srcFileType": ".txt",
        "dynacat": "汉代之后",
        "school": "隋唐"
    },
    "yiwen-leiju": {
        "eng": "yiwen-leiju",
        "dtv": "624",
        "dts": "624",
        "chn": "艺文类聚",
        "txtlen": 900237,
        "srcDir": "../../ctext_postHan/1_Shui2Tang2/Yi4_Wen2_Lei4_Ju4/dwn_files/",
        "srcFileType": ".txt",
        "dynacat": "汉代之后",
        "school": "隋唐"
    },
    "tongdian": {
        "eng": "tongdian",
        "dtv": "801",
        "dts": "801",
        "chn": "通典",
        "txtlen": 1606395,
        "srcDir": "../../ctext_postHan/1_Shui2Tang2/Tong1_Dian3/dwn_files/",
        "srcFileType": ".txt",
        "dynacat": "汉代之后",
        "school": "隋唐"
    },
    "yilin": {
        "eng": "yilin",
        "dtv": "770",
        "dts": "770",
        "chn": "意林",
        "txtlen": 46723,
        "srcDir": "../../ctext_postHan/1_Shui2Tang2/Yi4_Lin2/dwn_files/",
        "srcFileType": ".txt",
        "dynacat": "汉代之后",
        "school": "儒家"
    },
    "yinfujing": {
        "eng": "yinfujing",
        "dtv": "700",
        "dts": "700",
        "chn": "黄帝阴符经",
        "txtlen": 432,
        "srcDir": "../../ctext_postHan/1_Shui2Tang2/Huang2_Di4_Yin1_Fu2_Jing1/dwn_files/",
        "srcFileType": ".txt",
        "dynacat": "汉代之后",
        "school": "隋唐"
    },
    "si-shu-zhang-ju-ji-zhu": {
        "eng": "si-shu-zhang-ju-ji-zhu",
        "dtv": "1150",
        "dts": "1150",
        "chn": "四书章句集注",
        "txtlen": 200698,
        "srcDir": "../../ctext_postHan/2_Song4_Ming2/Si4_Shu1_Zhang1_Ju4_Ji2_Zhu4/dwn_files/",
        "srcFileType": ".txt",
        "dynacat": "汉代之后",
        "school": "宋明"
    },
    "lunyu-zhushu": {
        "eng": "lunyu-zhushu",
        "dtv": "960",
        "dts": "960",
        "chn": "论语注疏",
        "txtlen": 161597,
        "srcDir": "../../ctext_postHan/2_Song4_Ming2/Lun2_Yu3_Zhu4_Shu1/dwn_files/",
        "srcFileType": ".txt",
        "dynacat": "汉代之后",
        "school": "儒家"
    },
    "san-zi-jing": {
        "eng": "three-character-classic",
        "dtv": "960",
        "dts": "960",
        "chn": "三字经",
        "txtlen": "1068",
        "srcDir": "../../ctext_postHan/2_Song4_Ming2/San1_Zi4_Jing1/dwn_files/",
        "srcFileType": ".txt",
        "dynacat": "汉代之后",
        "school": "儒家"
    },
    "xiyouji": {
        "eng": "xiyouji",
        "dtv": "1520",
        "dts": "1520",
        "chn": "西游记",
        "txtlen": 588880,
        "srcDir": "../../ctext_postHan/XiYouJi/XiYouJi100",
        "srcFileType": ".txt",
        "dynacat": "汉代之后",
        "school": "佛教"
    },
    "sanguo-yanyi": {
        "eng": "sanguo-yanyi",
        "dtv": "1350",
        "dts": "1350",
        "chn": "三国演义",
        "txtlen": 484233,
        "srcDir": "../../ctext_postHan/SanGuoYanYi/sanguoyanyi120",
        "srcFileType": ".txt",
        "dynacat": "汉代之后",
        "school": ""
    },
    "fengshen-yanyi": {
        "eng": "fengshen-yanyi",
        "dtv": "-800",
        "dts": "1520, 封神演义,一般俗称《封神榜》，又名《商周列国全传》、《武王伐纣外史》",
        "chn": "封神演义",
        "txtlen": 486809,
        "srcDir": "../../ctext_postHan/FengShen_YanYi/FengShenYanYi100",
        "srcFileType": ".txt",
        "dynacat": "汉代之后",
        "school": "宋明"
    },
    "guangyun": {
        "eng": "guangyun",
        "dtv": "1007",
        "dts": "1007",
        "chn": "广韵",
        "txtlen": 221954,
        "srcDir": "../../ctext_postHan/2_Song4_Ming2/Guang3_Yun4/dwn_files/",
        "srcFileType": ".txt",
        "dynacat": "汉代之后",
        "school": "宋明"
    },
    "xiaojing-zhushu": {
        "eng": "xiaojing-zhushu",
        "dtv": "960",
        "dts": "960",
        "chn": "孝经注疏",
        "txtlen": 47290,
        "srcDir": "../../ctext_postHan/2_Song4_Ming2/Xiao4_Jin1_Zhu4_Shu4/dwn_files/",
        "srcFileType": ".txt",
        "dynacat": "汉代之后",
        "school": "宋明"
    },
    "taiping-yulan": {
        "eng": "taiping-yulan",
        "dtv": "977",
        "dts": "977",
        "chn": "太平御览",
        "txtlen": 3790869,
        "srcDir": "../../ctext_postHan/2_Song4_Ming2/Tai4_Ping2_Yu4_Lan3/dwn_files/",
        "srcFileType": ".txt",
        "dynacat": "汉代之后",
        "school": "宋明"
    },
    "taiping-guanji": {
        "eng": "taiping-guangji",
        "dtv": "977",
        "dts": "977",
        "chn": "太平广记",
        "txtlen": 1580001,
        "srcDir": "../../ctext_postHan/2_Song4_Ming2/Tai4_Ping2_Yu4_Lan3/dwn_files/",
        "srcFileType": ".txt",
        "dynacat": "汉代之后",
        "school": "宋明"
    },
    "zhuzi-yulei": {
        "eng": "zhuzi-yulei",
        "dtv": "1270",
        "dts": "1270",
        "chn": "朱子语类",
        "txtlen": 1563270,
        "srcDir": "../../ctext_postHan/ZhuZi_YuLei/dwn",
        "srcFileType": ".txt",
        "dynacat": "汉代之后",
        "school": "宋明"
    },
    "yingwengong": {
        "eng": "yingwengong",
        "dtv": "1061",
        "dts": "1061",
        "chn": "宋景文公笔记",
        "txtlen": 10769,
        "srcDir": "../../ctext_postHan/2_Song4_Ming2/Song4_Jing3_Wen2_Gong1_Bi3_Ji4/dwn_files/",
        "srcFileType": ".txt",
        "dynacat": "汉代之后",
        "school": "宋明"
    },
    "qijing": {
        "eng": "qijing",
        "dtv": "1010",
        "dts": "1010",
        "chn": "棋经",
        "txtlen": 1856,
        "srcDir": "../../ctext_postHan/2_Song4_Ming2/Qi2_Jin1/dwn_files/",
        "srcFileType": ".txt",
        "dynacat": "汉代之后",
        "school": "宋明"
    },
    "yulizi": {
        "eng": "yulizi",
        "dtv": "1375",
        "dts": "1375",
        "chn": "郁离子",
        "txtlen": 40673,
        "srcDir": "../../ctext_postHan/2_Song4_Ming2/Yu4_Li2_Zi/dwn_files/",
        "srcFileType": ".txt",
        "dynacat": "汉代之后",
        "school": "宋明"
    },
    "hongloumeng": {
        "eng": "hongloumeng",
        "dtv": "1780",
        "dts": "1780",
        "chn": "红楼梦",
        "txtlen": 715067,
        "srcDir": "../../ctext_postHan/HongLouMeng/hongloumeng120",
        "srcFileType": ".txt",
        "dynacat": "汉代之后",
        "school": "佛教"
    },
    "kangxi-zidian": {
        "eng": "kangxi-zidian",
        "dtv": "1710",
        "dts": "1710",
        "chn": "康熙字典",
        "txtlen": 2275843,
        "srcDir": "../../ctext_postHan/KangXi_ZiDian/dwn_files",
        "srcFileType": ".txt",
        "dynacat": "汉代之后",
        "school": "清代"
    },
    "rulin-waishi": {
        "eng": "rulin-waishi",
        "dtv": "1750",
        "dts": "1750",
        "chn": "儒林外史",
        "txtlen": 276374,
        "srcDir": "../../ctext_postHan/RuLin_WaiShi/dwnfiles/",
        "srcFileType": ".txt",
        "dynacat": "汉代之后",
        "school": "清代"
    },
    "mo-jing-jiao-shi": {
        "eng": "mo-jing-jiao-shi",
        "dtv": "1936",
        "dts": "1936",
        "chn": "墨经校释",
        "txtlen": "0",
        "srcDir": "../../ctext_postHan/4_Ming2_Guo2/Mo4_Jin1_Xiao4_Shi4/dwn_files/",
        "srcFileType": ".txt",
        "dynacat": "汉代之后",
        "school": "民国"
    },
    "jing-ping-mei": {
        "eng": "jing-ping-mei",
        "dtv": "1590",
        "dts": "1590",
        "chn": "金瓶梅",
        "txtlen": "630220",
        "srcDir": "../../ctext_postHan/JinPingMei/jinpingmei100",
        "srcFileType": ".txt",
        "dynacat": "",
        "school": ""
    },
    "QuanTangShi": {
        "eng": "QuanTangShi",
        "dtv": "800",
        "dts": "800",
        "chn": "全唐诗",
        "txtlen": 2893887,
        "srcDir": "../../ctext_postHan/QuanTangShi/files",
        "srcFileType": ".txt",
        "dynacat": "",
        "school": ""
    },
    "Mo4_Jin1_Xian2_Gu1": {
        "eng": "",
        "url": "https://ctext.org/mozi-jiangu/zhs",
        "dtv": "1893",
        "dts": "[清] 1893年 孙诒让著",
        "chn": "墨子闲诂",
        "txtlen": 0,
        "srcDir": "../../ctext_postHan/3_Qin1_Dai4/Mo4_Jin1_Xian2_Gu1/dwn_files/",
        "srcFileType": ".txt",
        "dynacat": "",
        "school": ""
    },
    "KarlMarx_ZiBenLun": {
        "eng": "",
        "dtv": "1840",
        "dts": "1840",
        "chn": "资本论",
        "txtlen": 0,
        "srcDir": "../../ctext_postHan/KarlMarx/ZiBenLun/files",
        "srcFileType": ".txt",
        "dynacat": "",
        "school": ""
    },
    "ShuiHuZhuan": {
        "eng": "",
        "dtv": "1296",
        "dts": "施耐庵（约1296年—约1370年）",
        "chn": "水浒传",
        "txtlen": 0,
        "srcDir": "../../ctext_postHan/ShuiHuZhuan/files",
        "srcFileType": ".txt",
        "dynacat": "",
        "school": ""
    },
    "foSutra": {
        "eng": "Sutra",
        "dtv": "968",
        "dts": "北宋开宝（968~975）年间，第一部木版雕印的大藏经问世后，历元、明、清至民国，共出版过木刻和排印本大藏经20种（一说21种）。",
        "chn": "大藏经(佛教经典总集)",
        "txtlen": 0,
        "srcDir": "../../fo/face_DaZangJing_Sutra/out/sub/utf8",
        "srcFileType": ".htm",
        "dynacat": "",
        "school": "佛教",
        "url": "http://sutra.foz.cn"
    },
    "MaoZeDongQuanJi": {
        "eng": "",
        "dtv": "1949",
        "dts": "",
        "chn": "毛泽东全集",
        "txtlen": 0,
        "srcDir": "../../maozedong/dwn/ndj/out/utf8_clean",
        "srcFileType": ".htm",
        "dynacat": "",
        "school": ""
    },
    "Mormon": {
        "eng": "",
        "dtv": "1820",
        "dts": "",
        "chn": "摩门经",
        "txtlen": 0,
        "srcDir": "../../mormon/dwn/ndj/out/dwn_web/",
        "srcFileType": ".htm",
        "dynacat": "",
        "school": "",
        "doctype": "misc",
        "author": "Joseph",
        "title": "C"
    },
    "Quran": {
        "eng": "",
        "dtv": "1949",
        "dts": "",
        "chn": "可兰经",
        "txtlen": 0,
        "srcDir": "../../quran/chn",
        "srcFileType": ".js",
        "dynacat": "",
        "school": ""
    },
    "CUVS_nt": {
        "eng": "CUVS_NT",
        "dtv": "1911",
        "dts": "1911",
        "chn": "HeHeBen",
        "txtlen": 0,
        "srcDir": "../../../../github/wdingbox/bible_obj_lib/jsdb/jsBibleObj/",
        "srcFileType": ".js",
        "srcFileNameKeyStr": "CUVS_nt",
        "dynacat": "",
        "school": "基督教"
    },
    "CUVS_ot": {
        "eng": "CUVS_OT",
        "dtv": "1911",
        "dts": "1911",
        "chn": "HeHeBen",
        "txtlen": 0,
        "srcDir": "../../../../github/wdingbox/bible_obj_lib/jsdb/jsBibleObj/",
        "srcFileType": ".js",
        "srcFileNameKeyStr": "CUVS_ot",
        "dynacat": "",
        "school": "基督教"
    },
    "STUS_nt": {
        "eng": "STUS_NT",
        "dtv": "1911",
        "dts": "1911",
        "chn": "SiTuo",
        "txtlen": 0,
        "srcDir": "../../../../github/wdingbox/bible_obj_lib/jsdb/jsBibleObj/",
        "srcFileType": ".js",
        "srcFileNameKeyStr": "STUS_nt",
        "dynacat": "",
        "school": "基督教"
    },
    "STUS_ot": {
        "eng": "STUS_OT",
        "dtv": "1911",
        "dts": "1911",
        "chn": "SiTuo",
        "txtlen": 0,
        "srcDir": "../../../../github/wdingbox/bible_obj_lib/jsdb/jsBibleObj/",
        "srcFileType": ".js",
        "srcFileNameKeyStr": "STUS_ot",
        "dynacat": "",
        "school": "基督教"
    },
    "WLVS_nt": {
        "eng": "WLVS_NT",
        "dtv": "1911",
        "dts": "1911",
        "chn": "SiTuo",
        "txtlen": 0,
        "srcDir": "../../../../github/wdingbox/bible_obj_lib/jsdb/jsBibleObj/",
        "srcFileType": ".js",
        "srcFileNameKeyStr": "WLVS_nt",
        "dynacat": "",
        "school": "基督教"
    },
    "WLVS_ot": {
        "eng": "WLVS_OT",
        "dtv": "1911",
        "dts": "1911",
        "chn": "SiTuo",
        "txtlen": 0,
        "srcDir": "../../../../github/wdingbox/bible_obj_lib/jsdb/jsBibleObj/",
        "srcFileType": ".js",
        "srcFileNameKeyStr": "WLVS_ot",
        "dynacat": "",
        "school": "基督教"
    },
    "_all_": {
        "dtv": "0",
        "chn": "_all_",
        "srcDir": "frqDocs"
    },
    "_all_BC": {
        "dtv": "-1",
        "chn": "_all_BC",
        "srcDir": "frqDocs"
    },
    "_all_AD": {
        "dtv": "1",
        "chn": "_all_AD",
        "srcDir": "frqDocs"
    },
    "_all_random": {
        "dtv": "1",
        "chn": "_all_random",
        "srcDir": "frqDocs"
    },
    "_all_school_Ru": {
        "dtv": "-1",
        "chn": "_school_Ru",
        "srcDir": "frqDocs"
    },
    "_all_school_Dao": {
        "dtv": "-1",
        "chn": "_school_Dao",
        "srcDir": "frqDocs"
    },
    "_all_school_Fa": {
        "dtv": "-1",
        "chn": "_school_Fa",
        "srcDir": "frqDocs"
    },
    "_all_school_Mo": {
        "dtv": "-1",
        "chn": "_school_Mo",
        "srcDir": "frqDocs"
    },
    "_all_school_Za": {
        "dtv": "-1",
        "chn": "_school_Za",
        "srcDir": "frqDocs"
    },
    "_all_school_Military": {
        "dtv": "-1",
        "chn": "_school_Military",
        "srcDir": "frqDocs"
    },
    "_all_school_History": {
        "dtv": "-1",
        "chn": "_school_History",
        "srcDir": "frqDocs"
    }
}