var _aux_doc_dat=
{
    "italics": {
        "Ben":0,
        "Huios":0,
        "huios":0,
        "Fu":0,
        "Zhi ":0,
        "XiAn":0,
        "Meng":0,
        "Kong":0,
        "Lao":0,
        "Ru":0,
        "Yue":0,
        "LuXun":0,
        "FuSiNian":0,
        "Yuan ZhiMing":0,
        "DaoDeJing":0,
        "GongZi":0,
        "TaiZi":0,
        "FuZi":0,
        "WangZi":0,
        "TianZi":0,
        "LunYu":0,
        "SanZiJing":0,
        "HaiDaoSuanJing":0,
        "ZhuangZi":0,
        "Han":0,
        "ZiYue":0,
        "LieZi":0,
        "YuGonYiShan":0,
        "Mao ZeDong":0,
        "Tian Mingjian":0,
        "Deng XiaoPing":0,
        "Zhang BoLi":0,
        "KongQiu":0,
        "YiRen":0,
        "JunZi":0,
        "Qin": 0,
        "HanShu": 0,
        "anno": 0,
        "Domini": 0,
        "QinHan": 0,
        "KongZi": 0,
        "MengZi": 0,
        "LaoZi": 0,
        "Zi": 0,
        "Er":0,
        "Ren":0,
        "ShiJi":0,
        "LinYuTang":0,
        "QianXuanTong":0,
        "ChunQiu":0,
        "ZhouLi":0,
        "KongZiJiaYu":0,
        "ShangShu":0,
        "PinYin":0,
        "A Comparative Study of the Concept of Wisdom on the Book of Wisdom and the Tad-Teh-Ching":0,
        "The Daoism: The Parting of the Way":0,
        "brookelester":0
    }
}