var prov_quo = {


    "father/mother 父亲/母亲": {
        "1:8": "我儿、要听你父亲的训诲、不可离弃你母亲的法则〔或作指教〕．",
        "4:3": "我在父亲面前为孝子、在母亲眼中为独一的娇儿。",
        "4:4": "父亲教训我说、你心要存记我的言语、遵守我的命令、便得存活。",
        "6:20": "我儿、要谨守你父亲的诫命、不可离弃你母亲的法则．〔或作指教〕",
        "10:1": "所罗门的箴言。智慧之子、使父亲欢乐．愚昧之子、叫母亲担忧。",
        "15:20": "智慧子使父亲喜乐．愚昧人藐视母亲。",
        "17:25": "愚昧子使父亲愁烦、使母亲忧苦。",
        "19:26": "虐待父亲、撵出母亲的、是贻羞致辱之子。",
        "20:20": "咒骂父母的、他的灯必灭、变为漆黑的黑暗。",
        "23:22": "你要听从生你的父亲．你母亲老了、也不可藐视他。",
        "23:25": "你要使父母欢喜．使生你的快乐。",
        "28:7": "谨守律法的是智慧之子．与贪食人作伴的、却羞辱其父。",
        "28:24": "偷窃父母的、说、这不是罪．此人就是与强盗同类。",
        "29:3": "爱慕智慧的、使父亲喜乐．与妓女结交的、却浪费钱财。",
        "29:15": "杖打和责备、能加增智慧．放纵的儿子、使母亲羞愧。",
        "30:11": "有一宗人、〔宗原文作代下同〕咒诅父亲、不给母亲祝福。",
        "30:17": "戏笑父亲、藐视而不听从母亲的、他的眼睛、必为谷中的乌鸦啄出来、为鹰雏所吃。",
        "31:1": "利慕伊勒王的言语、是他母亲教训他的真言。"
    },


    //妻
    "wife 妻/丈夫": {
        "5:18": "要使你的泉源蒙福．要喜悦你幼年所娶的妻。",
        "6:29": "亲近邻舍之妻的、也是如此．凡挨近他的、不免受罚。",
        "18:22": "得着贤妻的、是得着好处、也是蒙了耶和华的恩惠。",
        "19:13": "愚昧的儿子、是父亲的祸患．妻子的争吵、如雨连连滴漏。",
        "19:14": "房屋钱财、是祖宗所遗留的．惟有贤慧的妻、是耶和华所赐的。",

        "7:19": "因为我丈夫不在家、出门行远路．",
        "12:4": "才德的妇人、是丈夫的冠冕．贻羞的妇人、如同朽烂在他丈夫的骨中。",
        "31:11": "他丈夫心里倚靠他、必不缺少利益．",
        "31:12": "他一生使丈夫有益无损．",
        "31:23": "他丈夫在城门口与本地的长老同坐、为众人所认识。",
        "31:28": "他的儿女起来称他有福．他的丈夫也称赞他、"
    },


    //妇
    "woman 妇人":
    {
        "9:13": "愚昧的妇人喧嚷．他是愚蒙、一无所知。",
        "11:16": "恩德的妇女得尊荣．强暴的男子得资财。",
        "11:22": "妇女美貌而无见识、如同金环带在猪鼻上。",
        "12:4": "才德的妇人、是丈夫的冠冕．贻羞的妇人、如同朽烂在他丈夫的骨中。",
        "14:1": "智慧妇人、建立家室．愚妄妇人、亲手拆毁。",
        "15:25": "耶和华必拆毁骄傲人的家．却要立定寡妇的地界。",
        "21:9": "宁可住在房顶的角上、不在宽阔的房屋、与争吵的妇人同住。",
        "21:19": "宁可住在旷野、不与争吵使气的妇人同住。",
        "25:24": "宁可住在房顶的角上、不在宽阔的房屋与争吵的妇人同住。",
        "27:15": "大雨之日连连滴漏、和争吵的妇人一样．",
        "31:3": "不要将你的精力给妇女、也不要有败坏君王的行为。",
        "31:10": "才德的妇人谁能得着呢．他的价值远胜过珍珠．",
        "31:30": "艳丽是虚假的．美容是虚浮的．惟敬畏耶和华的妇女、必得称赞。"
    },
    "son 儿子": {
        "1:1": "以色列王大卫儿子所罗门的箴言．",
        "3:12": "因为耶和华所爱的、他必责备．正如父亲责备所喜爱的儿子。",
        "13:24": "不忍用杖打儿子的、是恨恶他．疼爱儿子的、随时管教。",
        "19:13": "愚昧的儿子、是父亲的祸患．妻子的争吵、如雨连连滴漏。",
        "19:18": "趁有指望、管教你的儿子．你的心不可任他死亡。",
        "22:6": "教养孩童、使他走当行的道、就是到老他也不偏离",
        "22:15": "愚蒙迷住孩童的心、用管教的杖可以远远赶除。",
        "23:13": "不可不管教孩童、你用杖打他、他必不至于死。",
        "23:14": "你要用杖打他、就可以救他的灵魂免下阴间。",
        "23:24": "义人的父亲、必大得快乐．人生智慧的儿子、必因他欢喜。",
        "29:15": "杖打和责备、能加增智慧．放纵的儿子、使母亲羞愧。",
        "29:17": "管教你的儿子、他就使你得安息、也必使你心里喜乐。",
        "29:21": "人将仆人从小娇养、这仆人终久必成了他的儿子。",
        "30:1": "雅基的儿子亚古珥的言语就是真言。这人对以铁和乌甲说、",
        "30:4": "谁升天又降下来．谁聚风在掌握中．谁包水在衣服里．谁立定地的四极．他名叫甚么．他儿子名叫甚么．你知道么。"
    },
    "children 儿女":
    {
        "14:26": "敬畏耶和华的、大有倚靠．他的儿女、也有避难所。",
        "17:6": "子孙为老人的冠冕．父亲是儿女的荣耀。",
        "31:28": "他的儿女起来称他有福．他的丈夫也称赞他、"
    },
    "longevity (长寿)":
    {
        "3:2": "因为他必将长久的日子、生命的年数、与平安、加给你。",
        "3:16": "他右手有长寿．左手有富贵。",
        "4:10": "我儿、你要听受我的言语、就必延年益寿。",
        "9:11": "你借着我、日子必增多、年岁也必加添。",
        "10:27": "敬畏耶和华、使人日子加多．但恶人的年岁必被减少。",
        "28:16": "无知的君多行暴虐．以贪财为可恨的、必年长日久。"
    },

    "whitehairs 白发/老人":
    {
        "16:31": "白发是荣耀的冠冕．在公义的道上、必能得着。",
        "17:6": "子孙为老人的冠冕．父亲是儿女的荣耀。",
        "20:29": "强壮乃少年人的荣耀．白发为老年人的尊荣。",
        "22:6": "教养孩童、使他走当行的道、就是到老他也不偏离。",
        "23:22": "你要听从生你的父亲．你母亲老了、也不可藐视他。",
        "31:23": "他丈夫在城门口与本地的长老同坐、为众人所认识。"
    },

    "crown 冠冕":
    {
        "12:4": "才德的妇人、是丈夫的冠冕．贻羞的妇人、如同朽烂在他丈夫的骨中。",
        "14:18": "愚蒙人得愚昧为产业．通达人得知识为冠冕。",
        "14:24": "智慧人的财、为自己的冠冕．愚妄人的愚昧、终是愚昧。",
        "16:31": "白发是荣耀的冠冕．在公义的道上、必能得着。",
        "17:6": "子孙为老人的冠冕．父亲是儿女的荣耀。",
        "27:24": "因为资财不能永有．冠冕岂能存到万代。"
    },

    "friends 朋友":
    {
        "6:1": "我儿、你若为朋友作保、替外人击掌、",
        "6:3": "我儿、你既落在朋友手中、就当这样行、才可救自己．你要自卑、去恳求你的朋友．",
        "14:20": "贫穷人连邻舍也恨他．富足人朋友最多。",
        "17:17": "朋友乃时常亲爱．弟兄为患难而生。",
        "18:24": "滥交朋友的、自取败坏．但有一朋友、比弟兄更亲密。",
        "19:4": "财物使朋友增多．但穷人朋友远离。",
        "19:6": "好施散的、有多人求他的恩情．爱送礼的、人都为他的朋友。",
        "19:7": "贫穷人弟兄都恨他．何况他的朋友、更远离他．他用言语追随、他们却走了。",
        "27:6": "朋友加的伤痕出于忠诚．仇敌连连亲嘴、却是多余。",
        "27:9": "膏油与香料、使人心喜悦．朋友诚实的劝教、也是如此甘美。",
        "27:10": "你的朋友、和父亲的朋友、你都不可离弃．你遭难的日子、不要上弟兄的家去．相近的邻舍、强如远方的弟兄。",
        "27:14": "清晨起来、大声给朋友祝福的、就算是咒诅他。",
        "27:17": "铁磨铁、磨出刃来．朋友相感、〔原文作磨朋友的脸〕也是如此。"
    },

    "Jesus": {
        "8:1": "智慧岂不呼叫、聪明岂不发声。Doth not wisdom cry? and understanding put forth her voice?Does not wisdom call out? Does not understanding raise her voice?",
        "8:2": "他在道旁高处的顶上、在十字路口站立．She standeth in the top of high places, by the way in the places of the paths.On the heights along the way, where the paths meet, she takes her stand;",
        "8:3": "在城门旁、在城门口、在城门洞、大声说、She crieth at the gates, at the entry of the city, at the coming in at the doors.beside the gates leading into the city, at the entrances, she cries aloud:",
        "8:4": "众人哪、我呼叫你们．我向世人发声。Unto you, O men, I call; and my voice is to the sons of man.\"To you, O men, I call out; I raise my voice to all mankind.",
        "8:5": "说、愚蒙人哪、你们要会悟灵明．愚昧人哪、你们当心里明白。O ye simple, understand wisdom: and, ye fools, be ye of an understanding heart.You who are simple, gain prudence; you who are foolish, gain understanding.",
        "8:6": "你们当听、因我要说极美的话．我张嘴要论正直的事。Hear; for I will speak of excellent things; and the opening of my lips shall be right things.Listen, for I have worthy things to say; I open my lips to speak what is right.",
        "8:7": "我的口要发出真理．我的嘴憎恶邪恶。For my mouth shall speak truth; and wickedness is an abomination to my lips.My mouth speaks what is true, for my lips detest wickedness.",
        "8:8": "我口中的言语、都是公义、并无弯曲乖僻。All the words of my mouth are in righteousness; there is nothing froward or perverse in them.All the words of my mouth are just; none of them is crooked or perverse.",
        "8:9": "有聪明的以为明显、得知识的以为正直．They are all plain to him that understandeth, and right to them that find knowledge.To the discerning all of them are right; they are faultless to those who have knowledge.",
        "8:10": "你们当受我的教训、不受白银．宁得知识、胜过黄金。Receive my instruction, and not silver; and knowledge rather than choice gold.Choose my instruction instead of silver, knowledge rather than choice gold,",
        "8:11": "因为智慧比珍珠〔或作红宝石〕更美．一切可喜爱的、都不足与比较。For wisdom is better than rubies; and all the things that may be desired are not to be compared to it.for wisdom is more precious than rubies, and nothing you desire can compare with her.",
        "8:12": "我智慧以灵明为居所、又寻得知识和谋略。I wisdom dwell with prudence, and find out knowledge of witty inventions.\"I, wisdom, dwell together with prudence; I possess knowledge and discretion.",
        "8:13": "敬畏耶和华、在乎恨恶邪恶．那骄傲、狂妄、并恶道、以及乖谬的口、都为我所恨恶。The fear of the LORD is to hate evil: pride, and arrogancy, and the evil way, and the froward mouth, do I hate.To fear the Lord is to hate evil; I hate pride and arrogance, evil behavior and perverse speech.",
        "8:14": "我有谋略、和真知识．我乃聪明．我有能力。Counsel is mine, and sound wisdom: I am understanding; I have strength.Counsel and sound judgment are mine; I have understanding and power.",
        "8:15": "帝王借我坐国位．君王借我定公平。By me kings reign, and princes decree justice.By me kings reign and rulers make laws that are just;",
        "8:16": "王子和首领、世上一切的审判官、都是借我掌权。By me princes rule, and nobles, even all the judges of the earth.by me princes govern, and all nobles who rule on earth.",
        "8:17": "爱我的、我也爱他．恳切寻求我的、必寻得见。I love them that love me; and those that seek me early shall find me.I love those who love me, and those who seek me find me.",
        "8:18": "丰富尊荣在我．恒久的财并公义也在我。Riches and honour are with me; yea, durable riches and righteousness.With me are riches and honor, enduring wealth and prosperity.",
        "8:19": "我的果实胜过黄金．强如精金．我的出产超乎高银。My fruit is better than gold, yea, than fine gold; and my revenue than choice silver.My fruit is better than fine gold; what I yield surpasses choice silver.",
        "8:20": "我在公义的道上走、在公平的路中行．I lead in the way of righteousness, in the midst of the paths of judgment:I walk in the way of righteousness, along the paths of justice,",
        "8:21": "使爱我的承受货财、并充满他们的府库。That I may cause those that love me to inherit substance; and I will fill their treasures.bestowing wealth on those who love me and making their treasuries full.",
        "8:22": "在耶和华造化的起头、在太初创造万物之先、就有了我。The LORD possessed me in the beginning of his way, before his works of old.\"The Lord brought me forth as the first of his works, , before his deeds of old;",
        "8:23": "从亘古、从太初、未有世界以前、我已被立。I was set up from everlasting, from the beginning, or ever the earth was.I was appointed from eternity, from the beginning, before the world began.",
        "8:24": "没有深渊、没有大水的泉源、我已生出。When there were no depths, I was brought forth; when there were no fountains abounding with water.When there were no oceans, I was given birth, when there were no springs abounding with water;",
        "8:25": "大山未曾奠定、小山未有之先、我已生出。Before the mountains were settled, before the hills was I brought forth:before the mountains were settled in place, before the hills, I was given birth,",
        "8:26": "耶和华还没有创造大地、和田野、并世上的土质、我已生出。While as yet he had not made the earth, nor the fields, nor the highest part of the dust of the world.before he made the earth or its fields or any of the dust of the world.",
        "8:27": "他立高天、我在那里．他在渊面的周围、画出圆圈、When he prepared the heavens, I was there: when he set a compass upon the face of the depth:I was there when he set the heavens in place, when he marked out the horizon on the face of the deep,",
        "8:28": "上使穹苍坚硬、下使渊源稳固、When he established the clouds above: when he strengthened the fountains of the deep:when he established the clouds above and fixed securely the fountains of the deep,",
        "8:29": "为沧海定出界限、使水不越过他的命令、立定大地的根基．When he gave to the sea his decree, that the waters should not pass his commandment: when he appointed the foundations of the earth:when he gave the sea its boundary so the waters would not overstep his command, and when he marked out the foundations of the earth.",
        "8:30": "那时、我在他那里为工师、日日为他所喜爱、常常在他面前踊跃、Then I was by him, as one brought up with him: and I was daily his delight, rejoicing always before him;Then I was the craftsman at his side. I was filled with delight day after day, rejoicing always in his presence,",
        "8:31": "踊跃在他为人预备可住之地、也喜悦住在世人之间。Rejoicing in the habitable part of his earth; and my delights were with the sons of men.rejoicing in his whole world and delighting in mankind.",
        "8:32": "众子阿、现在要听从我．因为谨守我道的、便为有福。Now therefore hearken unto me, O ye children: for blessed are they that keep my ways.\"Now then, my sons, listen to me; blessed are those who keep my ways.",
        "8:33": "要听教训、就得智慧、不可弃绝。Hear instruction, and be wise, and refuse it not.Listen to my instruction and be wise; do not ignore it.",
        "8:34": "听从我、日日在我门口仰望、在我门框旁边等候的、那人便为有福。Blessed is the man that heareth me, watching daily at my gates, waiting at the posts of my doors.Blessed is the man who listens to me, watching daily at my doors, waiting at my doorway.",
        "8:35": "因为寻得我的、就寻得生命、也必蒙耶和华的恩惠。For whoso findeth me findeth life, and shall obtain favour of the LORD.For whoever finds me finds life and receives favor from the Lord .",
        "8:36": "得罪我的、却害了自己的性命．恨恶我的、都喜爱死亡。But he that sinneth against me wrongeth his own soul: all they that hate me love death.But whoever fails to find me harms himself; all who hate me love death.\""
    },

    "口 Language Art":
    {
        "18:4": "人口中的言语、如同深水．智慧的泉源、好像涌流的河水。The words of a man's mouth are as deep waters, and the wellspring of wisdom as a flowing brook.The words of a man's mouth are deep waters, but the fountain of wisdom is a bubbling brook.",
        "18:5": "瞻徇恶人的情面、偏断义人的案件、都为不善。It is not good to accept the person of the wicked, to overthrow the righteous in judgment.It is not good to be partial to the wicked or to deprive the innocent of justice.",
        "18:6": "愚昧人张嘴启争端、开口招鞭打。A fool's lips enter into contention, and his mouth calleth for strokes.A fool's lips bring him strife, and his mouth invites a beating.",
        "18:7": "愚昧人的口、自取败坏．他的嘴、是他生命的网罗。A fool's mouth is his destruction, and his lips are the snare of his soul.A fool's mouth is his undoing, and his lips are a snare to his soul.",
        "18:8": "传舌人的言语、如同美食、深入人的心腹。The words of a talebearer are as wounds, and they go down into the innermost parts of the belly.The words of a gossip are like choice morsels; they go down to a man's inmost parts.",
        "18:13": "未曾听完先回答的、便是他的愚昧、和羞辱。He that answereth a matter before he heareth it, it is folly and shame unto him.He who answers before listening- that is his folly and his shame.",
        "18:17": "先诉情由的、似乎有理．但邻舍来到、就察出实情。He that is first in his own cause seemeth just; but his neighbour cometh and searcheth him.The first to present his case seems right, till another comes forward and questions him.",
        "18:19": "弟兄结怨、劝他和好、比取坚固城还难．这样的争竞、如同坚寨的门闩。A brother offended is harder to be won than a strong city: and their contentions are like the bars of a castle.An offended brother is more unyielding than a fortified city, and disputes are like the barred gates of a citadel.",
        "18:20": "人口中所结的果子、必充满肚腹．他嘴所出的、必使他饱足。A man's belly shall be satisfied with the fruit of his mouth; and with the increase of his lips shall he be filled.From the fruit of his mouth a man's stomach is filled; with the harvest from his lips he is satisfied.",
        "18:21": "生死在舌头的权下、喜爱他的、必吃他所结的果子。Death and life are in the power of the tongue: and they that love it shall eat the fruit thereof.The tongue has the power of life and death, and those who love it will eat its fruit.",
        "18:23": "贫穷人说哀求的话．富足人用威吓的话回答。The poor useth intreaties; but the rich answereth roughly.A poor man pleads for mercy, but a rich man answers harshly.",
        "19:5": "作假见证的、必不免受罚．吐出谎言的、终不能逃脱。A false witness shall not be unpunished, and he that speaketh lies shall not escape.A false witness will not go unpunished, and he who pours out lies will not go free.",
        "19:7": "贫穷人弟兄都恨他．何况他的朋友、更远离他．他用言语追随、他们却走了。All the brethren of the poor do hate him: how much more do his friends go far from him? he pursueth them with words, yet they are wanting to him.A poor man is shunned by all his relatives- how much more do his friends avoid him! Though he pursues them with pleading, they are nowhere to be found.",
        "19:9": "作假见证的、不免受罚．吐出谎言的、也必灭亡。A false witness shall not be unpunished, and he that speaketh lies shall perish.A false witness will not go unpunished, and he who pours out lies will perish.",
        "19:13": "愚昧的儿子、是父亲的祸患．妻子的争吵、如雨连连滴漏。A foolish son is the calamity of his father: and the contentions of a wife are a continual dropping.A foolish son is his father's ruin, and a quarrelsome wife is like a constant dripping.",
        "19:28": "匪徒作见证戏笑公平．恶人的口吞下罪孽。An ungodly witness scorneth judgment: and the mouth of the wicked devoureth iniquity.A corrupt witness mocks at justice, and the mouth of the wicked gulps down evil.",
        "20:6": "人多述说自己的仁慈．但忠信人谁能遇着呢。Most men will proclaim every one his own goodness: but a faithful man who can find?Many a man claims to have unfailing love, but a faithful man who can find?",
        "20:9": "谁能说、我洁净了我的心．我脱净了我的罪。Who can say, I have made my heart clean, I am pure from my sin?Who can say, \"I have kept my heart pure; I am clean and without sin\"?",
        "20:15": "有金子和许多珍珠．〔或作红宝石〕惟有知识的嘴、乃为贵重的珍宝。There is gold, and a multitude of rubies: but the lips of knowledge are a precious jewel.Gold there is, and rubies in abundance, but lips that speak knowledge are a rare jewel.",
        "20:16": "谁为生人作保、就拿谁的衣服．谁为外人作保、谁就要承当。Take his garment that is surety for a stranger: and take a pledge of him for a strange woman.Take the garment of one who puts up security for a stranger; hold it in pledge if he does it for a wayward woman.",
        "20:17": "以虚谎而得的食物、人觉甘甜．但后来他的口、必充满尘沙。Bread of deceit is sweet to a man; but afterwards his mouth shall be filled with gravel.Food gained by fraud tastes sweet to a man, but he ends up with a mouth full of gravel.",
        "20:19": "往来传舌的、泄漏密事．大张嘴的不可与他结交。He that goeth about as a talebearer revealeth secrets: therefore meddle not with him that flattereth with his lips.A gossip betrays a confidence; so avoid a man who talks too much.",
        "20:20": "咒骂父母的、他的灯必灭、变为漆黑的黑暗。Whoso curseth his father or his mother, his lamp shall be put out in obscure darkness.If a man curses his father or mother, his lamp will be snuffed out in pitch darkness.",
        "20:22": "你不要说、我要以恶报恶．要等候耶和华、他必拯救你。Say not thou, I will recompense evil; but wait on the LORD, and he shall save thee.Do not say, \"I'll pay you back for this wrong!\" Wait for the Lord , and he will deliver you.",
        "20:25": "人冒失说、这是圣物、许愿之后才查问、就是自陷网罗。It is a snare to the man who devoureth that which is holy, and after vows to make enquiry.It is a trap for a man to dedicate something rashly and only later to consider his vows.",
        "21:6": "用诡诈之舌求财的、就是自己取死．所得之财、乃是吹来吹去的浮云。The getting of treasures by a lying tongue is a vanity tossed to and fro of them that seek death.A fortune made by a lying tongue is a fleeting vapor and a deadly snare.",
        "21:9": "宁可住在房顶的角上、不在宽阔的房屋、与争吵的妇人同住。It is better to dwell in a corner of the housetop, than with a brawling woman in a wide house.Better to live on a corner of the roof than share a house with a quarrelsome wife.",
        "21:13": "塞耳不听穷人哀求的、他将来呼吁也不蒙应允。Whoso stoppeth his ears at the cry of the poor, he also shall cry himself, but shall not be heard.If a man shuts his ears to the cry of the poor, he too will cry out and not be answered.",
        "21:19": "宁可住在旷野、不与争吵使气的妇人同住。It is better to dwell in the wilderness, than with a contentious and an angry woman.Better to live in a desert than with a quarrelsome and ill-tempered wife.",
        "21:23": "谨守口与舌的、就保守自己免受灾难。Whoso keepeth his mouth and his tongue keepeth his soul from troubles.He who guards his mouth and his tongue keeps himself from calamity.",
        "21:28": "作假见证的必灭亡．惟有听真情而言的、其言长存。A false witness shall perish: but the man that heareth speaketh constantly.A false witness will perish, and whoever listens to him will be destroyed forever.",
        "22:6": "教养孩童、使他走当行的道、就是到老他也不偏离。Train up a child in the way he should go: and when he is old, he will not depart from it.Train a child in the way he should go, and when he is old he will not turn from it.",
        "22:11": "喜爱清心的人、因他嘴上的恩言、王必与他为友。He that loveth pureness of heart, for the grace of his lips the king shall be his friend.He who loves a pure heart and whose speech is gracious will have the king for his friend.",
        "22:12": "耶和华的眼目、眷顾聪明人．却倾败奸诈人的言语。The eyes of the LORD preserve knowledge, and he overthroweth the words of the transgressor.The eyes of the Lord keep watch over knowledge, but he frustrates the words of the unfaithful.",
        "22:13": "懒惰人说、外头有狮子、我在街上、就必被杀。The slothful man saith, There is a lion without, I shall be slain in the streets.The sluggard says, \"There is a lion outside!\" or, \"I will be murdered in the streets!\"",
        "22:14": "淫妇的口为深坑、耶和华所憎恶的、必陷在其中。The mouth of strange women is a deep pit: he that is abhorred of the LORD shall fall therein.The mouth of an adulteress is a deep pit; he who is under the Lord 's wrath will fall into it.",
        "22:17": "你须侧耳听受智慧人的言语、留心领会我的知识．Bow down thine ear, and hear the words of the wise, and apply thine heart unto my knowledge.Pay attention and listen to the sayings of the wise; apply your heart to what I teach,",
        "22:18": "你若心中存记、嘴上咬定、这便为美。For it is a pleasant thing if thou keep them within thee; they shall withal be fitted in thy lips.for it is pleasing when you keep them in your heart and have all of them ready on your lips.",
        "22:19": "我今日以此特特指教你、为要使你倚靠耶和华。That thy trust may be in the LORD, I have made known to thee this day, even to thee.So that your trust may be in the Lord , I teach you today, even you.",
        "22:21": "要使你知道真言的实理、你好将真言回复那打发你来的人。That I might make thee know the certainty of the words of truth; that thou mightest answer the words of truth to them that send unto thee?teaching you true and reliable words, so that you can give sound answers to him who sent you?",
        "22:23": "因耶和华必为他辨屈．抢夺他的、耶和华必夺取那人的命。For the LORD will plead their cause, and spoil the soul of those that spoiled them.for the Lord will take up their case and will plunder those who plunder them.",
        "22:26": "不要与人击掌、不要为欠债的作保。Be not thou one of them that strike hands, or of them that are sureties for debts.Do not be a man who strikes hands in pledge or puts up security for debts;",
        "23:7": "因为他心怎样思量、他为人就是怎样．他虽对你说、请吃、请喝、他的心却与你相背。For as he thinketh in his heart, so is he: Eat and drink, saith he to thee; but his heart is not with thee.for he is the kind of man who is always thinking about the cost. \"Eat and drink,\" he says to you, but his heart is not with you.",
        "23:8": "你所吃的那点食物、必吐出来．你所说的甘美言语、也必落空。The morsel which thou hast eaten shalt thou vomit up, and lose thy sweet words.You will vomit up the little you have eaten and will have wasted your compliments.",
        "23:9": "你不要说话给愚昧人听．因他必藐视你智慧的言语。Speak not in the ears of a fool: for he will despise the wisdom of thy words.Do not speak to a fool, for he will scorn the wisdom of your words.",
        "23:12": "你要留心领受训诲。侧耳听从知识的言语。Apply thine heart unto instruction, and thine ears to the words of knowledge.Apply your heart to instruction and your ears to words of knowledge.",
        "23:16": "你的嘴若说正直话、我的心肠也必快乐。Yea, my reins shall rejoice, when thy lips speak right things.my inmost being will rejoice when your lips speak what is right.",
        "24:2": "因为他们的心、图谋强暴．他们的口、谈论奸恶。For their heart studieth destruction, and their lips talk of mischief.for their hearts plot violence, and their lips talk about making trouble.",
        "24:7": "智慧极高、非愚昧人所能及、所以在城门内、不敢开口。Wisdom is too high for a fool: he openeth not his mouth in the gate.Wisdom is too high for a fool; in the assembly at the gate he has nothing to say.",
        "24:12": "你若说、这事我未曾知道．那衡量人心的、岂不明白么．保守你命的岂不知道么．他岂不按各人所行、的报应各人么。If thou sayest, Behold, we knew it not; doth not he that pondereth the heart consider it? and he that keepeth thy soul, doth not he know it? and shall not he render to every man according to his works?If you say, \"But we knew nothing about this,\" does not he who weighs the heart perceive it? Does not he who guards your life know it? Will he not repay each person according to what he has done?",
        "24:24": "对恶人说、你是义人的、这人万民必咒诅、列邦必憎恶。He that saith unto the wicked, Thou art righteous; him shall the people curse, nations shall abhor him:Whoever says to the guilty, \"You are innocent\"- peoples will curse him and nations denounce him.",
        "24:25": "责备恶人的、必得喜悦．美好的福、也必临到他。But to them that rebuke him shall be delight, and a good blessing shall come upon them.But it will go well with those who convict the guilty, and rich blessing will come upon them.",
        "24:26": "应对正直的、犹如与人亲嘴。Every man shall kiss his lips that giveth a right answer.An honest answer is like a kiss on the lips.",
        "24:28": "不可无故作见证、陷害邻舍．也不可用嘴欺骗人。Be not a witness against thy neighbour without cause; and deceive not with thy lips.Do not testify against your neighbor without cause, or use your lips to deceive.",
        "24:29": "不可说、人怎样待我、我也怎样待他、我必照他所行的报复他。Say not, I will do so to him as he hath done to me: I will render to the man according to his work.Do not say, \"I'll do to him as he has done to me; I'll pay that man back for what he did.\"",

        "25:7": "宁可有人说请你上来、强如在你觐见的王子面前、叫你退下。For better it is that it be said unto thee, Come up hither; than that thou shouldest be put lower in the presence of the prince whom thine eyes have seen.it is better for him to say to you, \"Come up here,\" than for him to humiliate you before a nobleman. What you have seen with your eyes",
        "25:9": "你与邻舍争讼、要与他一人辩论．不可泄漏人的密事．Debate thy cause with thy neighbour himself; and discover not a secret to another:If you argue your case with a neighbor, do not betray another man's confidence,",
        "25:10": "恐怕听见的人骂你、你的臭名就难以脱离。Lest he that heareth it put thee to shame, and thine infamy turn not away.or he who hears it may shame you and you will never lose your bad reputation.",
        "25:11": "一句话说得合宜、就如金苹果在银网子里。A word fitly spoken is like apples of gold in pictures of silver.A word aptly spoken is like apples of gold in settings of silver.",
        "25:12": "智慧人的劝戒、在顺从的人耳中、好像金耳环、和精金的妆饰。As an earring of gold, and an ornament of fine gold, so is a wise reprover upon an obedient ear.Like an earring of gold or an ornament of fine gold is a wise man's rebuke to a listening ear.",
        "25:13": "忠信的使者、叫差他的人心里舒畅、就如在收割时、有冰雪的凉气。As the cold of snow in the time of harvest, so is a faithful messenger to them that send him: for he refresheth the soul of his masters.Like the coolness of snow at harvest time is a trustworthy messenger to those who send him; he refreshes the spirit of his masters.",
        "25:14": "空夸赠送礼物的、好像无雨的风云。Whoso boasteth himself of a false gift is like clouds and wind without rain.Like clouds and wind without rain is a man who boasts of gifts he does not give.",
        "25:15": "恒常忍耐、可以劝动君王．柔和的舌头、能折断骨头。By long forbearing is a prince persuaded, and a soft tongue breaketh the bone.Through patience a ruler can be persuaded, and a gentle tongue can break a bone.",
        "25:18": "作假见证陷害邻舍的、就是大槌、是利刀、是快箭。A man that beareth false witness against his neighbour is a maul, and a sword, and a sharp arrow.Like a club or a sword or a sharp arrow is the man who gives false testimony against his neighbor.",
        "25:20": "对伤心的人唱歌、就如冷天脱衣服、又如碱上倒醋。As he that taketh away a garment in cold weather, and as vinegar upon nitre, so is he that singeth songs to an heavy heart.Like one who takes away a garment on a cold day, or like vinegar poured on soda, is one who sings songs to a heavy heart.",
        "25:23": "北风生雨、谗谤人的舌头也生怒容。The north wind driveth away rain: so doth an angry countenance a backbiting tongue.As a north wind brings rain, so a sly tongue brings angry looks.",
        "25:24": "宁可住在房顶的角上、不在宽阔的房屋与争吵的妇人同住。It is better to dwell in the corner of the housetop, than with a brawling woman and in a wide house.Better to live on a corner of the roof than share a house with a quarrelsome wife.",
        "25:25": "有好消息从远方来、就如拿凉水给口渴的人喝。As cold waters to a thirsty soul, so is good news from a far country.Like cold water to a weary soul is good news from a distant land.",
        "26:4": "不要照愚昧人的愚妄话回答他、恐怕你与他一样。Answer not a fool according to his folly, lest thou also be like unto him.Do not answer a fool according to his folly, or you will be like him yourself.",
        "26:5": "要照愚昧人的愚妄话回答他、免得他自以为有智慧。Answer a fool according to his folly, lest he be wise in his own conceit.Answer a fool according to his folly, or he will be wise in his own eyes.",
        "26:7": "瘸子的脚、空存无用．箴言在愚昧人的口中也是如此。The legs of the lame are not equal: so is a parable in the mouth of fools.Like a lame man's legs that hang limp is a proverb in the mouth of a fool.",
        "26:9": "箴言在愚昧人的口中、好像荆棘刺入醉汉的手。As a thorn goeth up into the hand of a drunkard, so is a parable in the mouth of fools.Like a thornbush in a drunkard's hand is a proverb in the mouth of a fool.",
        "26:13": "懒惰人说、道上有猛狮、街上有壮狮。The slothful man saith, There is a lion in the way; a lion is in the streets.The sluggard says, \"There is a lion in the road, a fierce lion roaming the streets!\"",
        "26:15": "懒惰人放手在盘子里、就是向口撤回、也以为劳乏。The slothful hideth his hand in his bosom; it grieveth him to bring it again to his mouth.The sluggard buries his hand in the dish; he is too lazy to bring it back to his mouth.",
        "26:16": "懒惰人看自己、比七个善于应对的人更有智慧。The sluggard is wiser in his own conceit than seven men that can render a reason.The sluggard is wiser in his own eyes than seven men who answer discreetly.",
        "26:18": "人欺凌邻舍、却说、我岂不是戏耍吗。他就像疯狂的人抛掷火把、利箭、与杀人的兵器〔杀人的兵器原文作死亡〕。As a mad man who casteth firebrands, arrows, and death,Like a madman shooting firebrands or deadly arrows",
        "26:20": "火缺了柴、就必熄灭．无人传舌、争竞便止息。Where no wood is, there the fire goeth out: so where there is no talebearer, the strife ceaseth.Without wood a fire goes out; without gossip a quarrel dies down.",
        "26:21": "好争竞的人煽惑争端、就如余火加炭、火上加柴一样。As coals are to burning coals, and wood to fire; so is a contentious man to kindle strife.As charcoal to embers and as wood to fire, so is a quarrelsome man for kindling strife.",
        "26:22": "传舌人的言语、如同美食、深入人的心腹。The words of a talebearer are as wounds, and they go down into the innermost parts of the belly.The words of a gossip are like choice morsels; they go down to a man's inmost parts.",
        "26:23": "火热的嘴、奸恶的心、好像银渣包的瓦器。Burning lips and a wicked heart are like a potsherd covered with silver dross.Like a coating of glaze over earthenware are fervent lips with an evil heart.",
        "26:24": "怨恨人的用嘴粉饰、心里却藏着诡诈．He that hateth dissembleth with his lips, and layeth up deceit within him;A malicious man disguises himself with his lips, but in his heart he harbors deceit.",
        "26:25": "他用甜言蜜语、你不可信他、因为他心中有七样可憎恶的．When he speaketh fair, believe him not: for there are seven abominations in his heart.Though his speech is charming, do not believe him, for seven abominations fill his heart.",
        "26:26": "他虽用诡诈遮掩自己的怨恨、他的邪恶必在会中显露。Whose hatred is covered by deceit, his wickedness shall be shewed before the whole congregation.His malice may be concealed by deception, but his wickedness will be exposed in the assembly.",
        "26:28": "虚谎的舌、恨他所压伤的人．谄媚的口、败坏人的事。A lying tongue hateth those that are afflicted by it; and a flattering mouth worketh ruin.A lying tongue hates those it hurts, and a flattering mouth works ruin.",
        "27:1": "不要为明日自夸、因为一日要生何事、你尚且不能知道。Boast not thyself of to morrow; for thou knowest not what a day may bring forth.Do not boast about tomorrow, for you do not know what a day may bring forth.",
        "27:2": "要别人夸奖你、不可用口自夸．等外人称赞你、不可用嘴自称。Let another man praise thee, and not thine own mouth; a stranger, and not thine own lips.Let another praise you, and not your own mouth; someone else, and not your own lips.",
        "27:5": "当面的责备、强如背地的爱情。Open rebuke is better than secret love.Better is open rebuke than hidden love.",
        "27:6": "朋友加的伤痕出于忠诚．仇敌连连亲嘴、却是多余。Faithful are the wounds of a friend; but the kisses of an enemy are deceitful.Wounds from a friend can be trusted, but an enemy multiplies kisses.",
        "27:9": "膏油与香料、使人心喜悦．朋友诚实的劝教、也是如此甘美。Ointment and perfume rejoice the heart: so doth the sweetness of a man's friend by hearty counsel.Perfume and incense bring joy to the heart, and the pleasantness of one's friend springs from his earnest counsel.",
        "27:11": "我儿、你要作智慧人、好叫我的心欢喜、使我可以回答那讥诮我的人。My son, be wise, and make my heart glad, that I may answer him that reproacheth me.Be wise, my son, and bring joy to my heart; then I can answer anyone who treats me with contempt.",
        "27:14": "清晨起来、大声给朋友祝福的、就算是咒诅他。He that blesseth his friend with a loud voice, rising early in the morning, it shall be counted a curse to him.If a man loudly blesses his neighbor early in the morning, it will be taken as a curse.",
        "27:15": "大雨之日连连滴漏、和争吵的妇人一样．A continual dropping in a very rainy day and a contentious woman are alike.A quarrelsome wife is like a constant dripping on a rainy day;",
        "27:16": "想拦阻他的、便是拦阻风、也是右手抓油。Whosoever hideth her hideth the wind, and the ointment of his right hand, which bewrayeth itself.restraining her is like restraining the wind or grasping oil with the hand.",
        "27:21": "鼎为炼银、炉为炼金、人的称赞也试炼人。As the fining pot for silver, and the furnace for gold; so is a man to his praise.The crucible for silver and the furnace for gold, but man is tested by the praise he receives.",
        "28:9": "转耳不听律法的、他的祈祷也为可憎。He that turneth away his ear from hearing the law, even his prayer shall be abomination.If anyone turns a deaf ear to the law, even his prayers are detestable.",
        "28:23": "责备人的、后来蒙人喜悦、多于那用舌头谄媚人的。He that rebuketh a man afterwards shall find more favour than he that flattereth with the tongue.He who rebukes a man will in the end gain more favor than he who has a flattering tongue.",
        "28:24": "偷窃父母的、说、这不是罪．此人就是与强盗同类。Whoso robbeth his father or his mother, and saith, It is no transgression; the same is the companion of a destroyer.He who robs his father or mother and says, \"It's not wrong\"- he is partner to him who destroys.",
        "29:9": "智慧人与愚妄人相争、或怒、或笑、总不能使他止息。If a wise man contendeth with a foolish man, whether he rage or laugh, there is no rest.If a wise man goes to court with a fool, the fool rages and scoffs, and there is no peace.",
        "29:11": "愚妄人怒气全发．智慧人忍气含怒。A fool uttereth all his mind: but a wise man keepeth it in till afterwards.A fool gives full vent to his anger, but a wise man keeps himself under control.",
        "29:12": "君王若听谎言、他一切臣仆都是奸恶。If a ruler hearken to lies, all his servants are wicked.If a ruler listens to lies, all his officials become wicked.",
        "29:19": "只用言语、仆人不肯受管教、他虽然明白、也不留意。A servant will not be corrected by words: for though he understand he will not answer.A servant cannot be corrected by mere words; though he understands, he will not respond.",
        "29:20": "你见言语急躁的人么．愚昧人比他更有指望。Seest thou a man that is hasty in his words? there is more hope of a fool than of him.Do you see a man who speaks in haste? There is more hope for a fool than for him.",
        "29:22": "好气的人挑启争端．暴怒的人、多多犯罪。An angry man stirreth up strife, and a furious man aboundeth in transgression.An angry man stirs up dissension, and a hot-tempered one commits many sins.",
        "29:24": "人与盗贼分赃、是恨恶自己的性命．他听见叫人发誓的声音、却不言语。Whoso is partner with a thief hateth his own soul: he heareth cursing, and bewrayeth it not.The accomplice of a thief is his own enemy; he is put under oath and dare not testify.",
        "30:1": "雅基的儿子亚古珥的言语就是真言。这人对以铁和乌甲说、The words of Agur the son of Jakeh, even the prophecy: the man spake unto Ithiel, even unto Ithiel and Ucal,The sayings of Agur son of Jakehan oracle : This man declared to Ithiel, to Ithiel and to Ucal:",
        "30:5": "神的言语、句句都是炼净的、投靠他的、他便作他们的盾牌。Every word of God is pure: he is a shield unto them that put their trust in him.\"Every word of God is flawless; he is a shield to those who take refuge in him.",
        "30:6": "他的言语、你不可加添、恐怕他责备你、你就显为说谎言的。Add thou not unto his words, lest he reprove thee, and thou be found a liar.Do not add to his words, or he will rebuke you and prove you a liar.",
        "30:8": "求你使虚假和谎言远离我．使我也不贫穷、也不富足赐给我需用的饮食．Remove far from me vanity and lies: give me neither poverty nor riches; feed me with food convenient for me:Keep falsehood and lies far from me; give me neither poverty nor riches, but give me only my daily bread.",
        "30:9": "恐怕我饱足不认你、说、耶和华是谁呢．又恐怕我贫穷就偷窃、以致亵渎我　神的名。Lest I be full, and deny thee, and say, Who is the LORD? or lest I be poor, and steal, and take the name of my God in vain.Otherwise, I may have too much and disown you and say, 'Who is the Lord ?' Or I may become poor and steal, and so dishonor the name of my God.",
        "30:10": "你不要向主人谗谤仆人、恐怕他咒诅你、你便算为有罪。Accuse not a servant unto his master, lest he curse thee, and thou be found guilty.\"Do not slander a servant to his master, or he will curse you, and you will pay for it.",
        "30:11": "有一宗人、〔宗原文作代下同〕咒诅父亲、不给母亲祝福。There is a generation that curseth their father, and doth not bless their mother.\"There are those who curse their fathers and do not bless their mothers;",
        "30:14": "有一宗人、牙如剑、齿如刀、要吞灭地上的困苦人、和世间的穷乏人。There is a generation, whose teeth are as swords, and their jaw teeth as knives, to devour the poor from off the earth, and the needy from among men.those whose teeth are swords and whose jaws are set with knives to devour the poor from the earth, the needy from among mankind.",
        "30:32": "你若行事愚顽、自高自傲、或是怀了恶念、就当用手摀口。If thou hast done foolishly in lifting up thyself, or if thou hast thought evil, lay thine hand upon thy mouth.\"If you have played the fool and exalted yourself, or if you have planned evil, clap your hand over your mouth!",
        "31:1": "利慕伊勒王的言语、是他母亲教训他的真言。The words of king Lemuel, the prophecy that his mother taught him.The sayings of King Lemuel - an oracle his mother taught him:",
        "31:2": "我的儿阿、我腹中生的儿阿、我许愿得的儿阿、我当怎样教训你呢．What, my son? and what, the son of my womb? and what, the son of my vows?\"O my son, O son of my womb, O son of my vows,",
        "31:8": "你当为哑巴〔或作不能自辩的〕开口．为一切孤独的伸冤。Open thy mouth for the dumb in the cause of all such as are appointed to destruction.\"Speak up for those who cannot speak for themselves, for the rights of all who are destitute.",
        "31:9": "你当开口按公义判断、为困苦和穷乏的辨屈。Open thy mouth, judge righteously, and plead the cause of the poor and needy.Speak up and judge fairly; defend the rights of the poor and needy.\" Epilogue: The Wife of Noble Character",
        "31:26": "他开口就发智慧．他舌上有仁慈的法则．She openeth her mouth with wisdom; and in her tongue is the law of kindness.She speaks with wisdom, and faithful instruction is on her tongue.",
        "31:28": "他的儿女起来称他有福．他的丈夫也称赞他、Her children arise up, and call her blessed; her husband also, and he praiseth her.Her children arise and call her blessed; her husband also, and he praises her:",
        "31:29": "说、才德的女子很多、惟独你超过一切。Many daughters have done virtuously, but thou excellest them all.\"Many women do noble things, but you surpass them all.\""

    },

    "State/Politics":
    {
        "6:7": "蚂蚁没有元帅、没有官长、没有君王、Which having no guide, overseer, or ruler,It has no commander, no overseer or ruler,",
        "8:15": "帝王借我坐国位．君王借我定公平。By me kings reign, and princes decree justice.By me kings reign and rulers make laws that are just;",
        "8:16": "王子和首领、世上一切的审判官、都是借我掌权。By me princes rule, and nobles, even all the judges of the earth.by me princes govern, and all nobles who rule on earth.",
        "14:28": "帝王荣耀在乎民多．君王衰败在乎民少。In the multitude of people is the king's honour: but in the want of people is the destruction of the prince.A large population is a king's glory, but without subjects a prince is ruined.",
        "14:35": "智慧的臣子、蒙王恩惠．贻羞的仆人、遭其震怒。The king's favour is toward a wise servant: but his wrath is against him that causeth shame.A king delights in a wise servant, but a shameful servant incurs his wrath.",
        "16:10": "王的嘴中有神语．审判之时、他的口、必不差错。A divine sentence is in the lips of the king: his mouth transgresseth not in judgment.The lips of a king speak as an oracle, and his mouth should not betray justice.",
        "16:12": "作恶为王所憎恶．因国位是靠公义坚立。It is an abomination to kings to commit wickedness: for the throne is established by righteousness.Kings detest wrongdoing, for a throne is established through righteousness.",
        "16:13": "公义的嘴、为王所喜悦．说正直话的、为王所喜爱。Righteous lips are the delight of kings; and they love him that speaketh right.Kings take pleasure in honest lips; they value a man who speaks the truth.",
        "16:14": "王的震怒、如杀人的使者．但智慧人能止息王怒。The wrath of a king is as messengers of death: but a wise man will pacify it.A king's wrath is a messenger of death, but a wise man will appease it.",
        "16:15": "王的脸光、使人有生命．王的恩典、好像春云时雨。In the light of the king's countenance is life; and his favour is as a cloud of the latter rain.When a king's face brightens, it means life; his favor is like a rain cloud in spring.",
        "17:7": "愚顽人说美言本不相宜、何况君王说谎话呢。Excellent speech becometh not a fool: much less do lying lips a prince.Arrogant lips are unsuited to a foolhow much worse lying lips to a ruler!",
        "19:10": "愚昧人宴乐度日、是不合宜的．何况仆人管辖王子呢。Delight is not seemly for a fool; much less for a servant to have rule over princes.It is not fitting for a fool to live in luxury- how much worse for a slave to rule over princes!",
        "19:12": "王的忿怒、好像狮子吼叫．他的恩典、却如草上的甘露。The king's wrath is as the roaring of a lion; but his favour is as dew upon the grass.A king's rage is like the roar of a lion, but his favor is like dew on the grass.",
        "20:2": "王的威吓如同狮子吼叫．惹动他怒的、是自害己命。The fear of a king is as the roaring of a lion: whoso provoketh him to anger sinneth against his own soul.A king's wrath is like the roar of a lion; he who angers him forfeits his life.",
        "20:8": "王坐在审判的位上、以眼目驱散诸恶。A king that sitteth in the throne of judgment scattereth away all evil with his eyes.When a king sits on his throne to judge, he winnows out all evil with his eyes.",
        "20:26": "智慧的王、簸散恶人、用碌碡滚轧他们。A wise king scattereth the wicked, and bringeth the wheel over them.A wise king winnows out the wicked; he drives the threshing wheel over them.",
        "20:28": "王因仁慈和诚实、得以保全他的国位、也因仁慈立稳。Mercy and truth preserve the king: and his throne is upholden by mercy.Love and faithfulness keep a king safe; through love his throne is made secure.",
        "21:1": "王的心在耶和华手中、好像陇沟的水、随意流转。The king's heart is in the hand of the LORD, as the rivers of water: he turneth it whithersoever he will.The king's heart is in the hand of the Lord ; he directs it like a watercourse wherever he pleases.",
        "22:11": "喜爱清心的人、因他嘴上的恩言、王必与他为友。He that loveth pureness of heart, for the grace of his lips the king shall be his friend.He who loves a pure heart and whose speech is gracious will have the king for his friend.",
        "22:29": "你看见办事殷勤的人么、他必站在君王面前．必不站在下贱人面前。Seest thou a man diligent in his business? he shall stand before kings; he shall not stand before mean men.Do you see a man skilled in his work? He will serve before kings; he will not serve before obscure men.",
        "24:21": "我儿、你要敬畏耶和华与君王．不要与反复无常的人结交．My son, fear thou the LORD and the king: and meddle not with them that are given to change:Fear the Lord and the king, my son, and do not join with the rebellious,",
        "24:22": "因为他们的灾难、必忽然而起．耶和华与君王所施行的毁灭、谁能知道呢。For their calamity shall rise suddenly; and who knoweth the ruin of them both?for those two will send sudden destruction upon them, and who knows what calamities they can bring? Further Sayings of the Wise",
        "25:2": "将事隐秘、乃　神的荣耀．将事察清、乃君王的荣耀。It is the glory of God to conceal a thing: but the honour of kings is to search out a matter.It is the glory of God to conceal a matter; to search out a matter is the glory of kings.",
        "25:3": "天之高、地之厚、君王之心也测不透。The heaven for height, and the earth for depth, and the heart of kings is unsearchable.As the heavens are high and the earth is deep, so the hearts of kings are unsearchable.",
        "25:5": "除去王面前的恶人、国位就靠公义坚立。Take away the wicked from before the king, and his throne shall be established in righteousness.remove the wicked from the king's presence, and his throne will be established through righteousness.",
        "25:6": "不要在王面前妄自尊大．不要在大人的位上站立。Put not forth thyself in the presence of the king, and stand not in the place of great men:Do not exalt yourself in the king's presence, and do not claim a place among great men;",
        "25:7": "宁可有人说请你上来、强如在你觐见的王子面前、叫你退下。For better it is that it be said unto thee, Come up hither; than that thou shouldest be put lower in the presence of the prince whom thine eyes have seen.it is better for him to say to you, \"Come up here,\" than for him to humiliate you before a nobleman. What you have seen with your eyes",
        "25:15": "恒常忍耐、可以劝动君王．柔和的舌头、能折断骨头。By long forbearing is a prince persuaded, and a soft tongue breaketh the bone.Through patience a ruler can be persuaded, and a gentle tongue can break a bone.",
        "28:2": "邦国因有罪过、君王就多更换．因有聪明知识的人、国必长存。For the transgression of a land many are the princes thereof: but by a man of understanding and knowledge the state thereof shall be prolonged.When a country is rebellious, it has many rulers, but a man of understanding and knowledge maintains order.",
        "28:15": "暴虐的君王辖制贫民．好像吼叫的狮子、觅食的熊。As a roaring lion, and a ranging bear; so is a wicked ruler over the poor people.Like a roaring lion or a charging bear is a wicked man ruling over a helpless people.",
        "29:4": "王借公平、使国坚定．索要贿赂、使国倾败。The king by judgment establisheth the land: but he that receiveth gifts overthroweth it.By justice a king gives a country stability, but one who is greedy for bribes tears it down.",
        "29:12": "君王若听谎言、他一切臣仆都是奸恶。If a ruler hearken to lies, all his servants are wicked.If a ruler listens to lies, all his officials become wicked.",
        "29:14": "君王凭诚实判断穷人．他的国位、必永远坚立。The king that faithfully judgeth the poor, his throne shall be established for ever.If a king judges the poor with fairness, his throne will always be secure.",
        "29:26": "求王恩的人多．定人事乃在耶和华。Many seek the ruler's favour; but every man's judgment cometh from the LORD.Many seek an audience with a ruler, but it is from the Lord that man gets justice.",
        "30:31": "猎狗、公山羊、和无人能敌的君王。A greyhound; an he goat also; and a king, against whom there is no rising up.a strutting rooster, a he-goat, and a king with his army around him.",
        "31:3": "不要将你的精力给妇女、也不要有败坏君王的行为。Give not thy strength unto women, nor thy ways to that which destroyeth kings.do not spend your strength on women, your vigor on those who ruin kings.",
        "31:4": "利慕伊勒阿、君王喝酒、君王喝酒不相宜．王子说、浓酒在那里也不相宜．It is not for kings, O Lemuel, it is not for kings to drink wine; nor for princes strong drink:\"It is not for kings, O Lemuel- not for kings to drink wine, not for rulers to crave beer,"
    },
    "citizen":
    {
        "11:14": "无智谋、民就败落．谋士多、人便安居。",
        "11:26": "屯粮不卖的、民必咒诅他．情愿出卖的、人必为他祝福。",
        "14:28": "帝王荣耀在乎民多．君王衰败在乎民少。",
        "14:34": "公义使邦国高举．罪恶是人民的羞辱。",
        "24:24": "对恶人说、你是义人的、这人万民必咒诅、列邦必憎恶。",
        "28:3": "穷人欺压贫民、好像暴雨冲没粮食。",
        "28:15": "暴虐的君王辖制贫民．好像吼叫的狮子、觅食的熊。",
        "29:2": "义人增多、民就喜乐．恶人掌权、民就叹息。",
        "29:18": "没有异象、〔或作默示〕民就放肆．惟遵守律法的、便为有福。"
    },

    "Sex/Adultery": {

    }
}
