
var Fruits = {
    Love: {
        chn: "仁爱",
        href: "https://www.blueletterbible.org/lexicon/g26/kjv/tr/0-1/",
        gre: "ἀγάπη",
        lit: "agapē",
        positive: [
            "Love God",
            "Love Jesus",
            "Love the Spirit",
            "Love the Word (Logos)",
            "Love the Gospels",
            "Love the Kingdom of Heaven",
            "Love your Neighbors",
            "Love your Church",
            "Love your Service",
            "Love your Mission",
        ],
        negative: [
            "Status quo",
            "Food/Clothes",
            "Houses/Cars",
            "Fames/brand",
            "Money",
            "your Family",
            "your work",
            "patriotism",
            "self-sensational pleasure",
            "hobbies/ametures",
        ],
    },
    joy: {
        chn: `喜乐`,
        href: "https://www.blueletterbible.org/lexicon/g5479/kjv/tr/0-1/",
        gre: "χαρά",
        lit: "chara",
        positive: [
            "personal Christian life",
            "church life",
            "fellowship life",
            "missionary life",
            "service life",
            "family whorship life",
            "faithful life",
        ],
        negative: [
            "rich material",
            "new house",
            "successful career",
            "nice fame/name",
            "money",
            "family",
            "children",
        ],
    },

    peace: {
        chn: `和平`,
        href: "https://www.blueletterbible.org/lexicon/g1515/kjv/tr/0-1/",
        gre: "εἰρήνη",
        lit: "eirēnē",
        positive: [
            "God",
            "Jesus",
            "the Word",
            "the Spirit",
            "Faith",
            "Persecution",
            "Disasters",
        ],
        negative: [
            "Competative",
            "for prosperity(wealth)",
            "for smooth life",
            "for elder life",
            "for personal happiness",
            "for nation development",
            "for culture",
        ],
    },


    patience: {
        chn: `忍耐`,
        href: "https://www.blueletterbible.org/lexicon/g3115/kjv/tr/0-1/",
        gre: "μακροθυμία",
        lit: "makrothymia",
        positive: [
            "longsuffering",
            "endurance",
            "constancy",
            "steadfastness",
            "perseverance",
            "forbearance",
            "slowness in persecution",],
        negative: [
            "Competative",
            "for prosperity(wealth)",
            "for smooth life",
            "for elder life",
            "for personal happiness",
            "for nation development",
            "for culture",
        ],
    },


    kindness: {
        chn: "恩慈",
        href: "https://www.blueletterbible.org/lexicon/g5544/kjv/tr/0-1/",
        gre: "χρηστότης",
        lit: "khray-stot'-ace",
        positive: [
            "employed",
            "useful",
            "better",
            "easy",
            "gracious",
            "fit for use",
            "virtuous",
            "good",
            "manageable",
            "mild",
            "pleasant (as opp. to harsh, hard sharp, bitter)",
            "benevolent",
        ],

        negative: [
            "Competative",
            "for prosperity(wealth)",
            "for smooth life",
            "for elder life",
            "for personal happiness",
            "for nation development",
            "for culture",
        ],
    },

    goodness: {
        chn: `良善`,
        href: "https://www.blueletterbible.org/lexicon/g19/kjv/tr/0-1/",
        gre: "ἀγαθωσύνη",
        lit: "(ag-ath-o-soo'-nay)",

        positive: [
            "uprightness",
            "righteousness",
            "just",
            "goodness",
            "kindness",
            "virtue",
            "beneficence",

        ],
        negative: [
            "Competative",
            "for prosperity(wealth)",
            "for smooth life",
            "for elder life",
            "for personal happiness",
            "for nation development",
            "for culture",
        ],
    },

    faithful: {
        chn: `信实`,
        href: "https://www.blueletterbible.org/lexicon/g4102/kjv/tr/0-1/",
        gre: "πίστις",
        lit: "pistis",

        positive: [
            "fidelity",
            "belief",
            "trust ",
            "living life",
            "action",
        ],
        negative: [
            "Competative",
            "for prosperity(wealth)",
            "for smooth life",
            "for elder life",
            "for personal happiness",
            "for nation development",
            "for culture",
        ],

    },

    gentleness: {
        chn: `温柔`,
        href: "https://www.blueletterbible.org/lexicon/g4236/kjv/tr/0-1/",
        gre: "πραότης",
        lit: "prah-ot'-ace",
        positive: [
            "mildness",
            "meekness",
            "gentleness",
        ],
        negative: [
            "Competative",
            "for prosperity(wealth)",
            "for smooth life",
            "for elder life",
            "for personal happiness",
            "for nation development",
            "for culture",
        ],
    },

    "self-controll": {
        chn: `节制`,
        href: "https://www.blueletterbible.org/lexicon/g1466/kjv/tr/0-1/",
        gre: "ἐγκράτεια",
        lit: "eng-krat'-i-ah",

        positive: [
            "masters desires",
            "masters passions",
            "masters sensual appetites",
        ],
        negative: [
            "Competative",
            "for prosperity(wealth)",
            "for smooth life",
            "for elder life",
            "for personal happiness",
            "for nation development",
            "for culture",
        ],
    },
}